### ISSUE TITLE
System.InvalidOperationException: No publishers configured for `X` (7.0.0-alpha0359)

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureServiceBus#177]
Getting the exception *System.InvalidOperationException: No publishers configured for `X`* during startup.

- The exception results in the process to die.

This does work for the ASB transport for NSB 5 and also works for all other transports for NSB V6.

## Event

```
partial class GatedPublishRunner : LoopRunner
{
    public class Event : IEvent
    {
    }
}
```

## Mappings

The code is used to define the mappings which is based from the code available at : http://docs.particular.net/nservicebus/messaging/message-owner

```
using System.Configuration;
using NServiceBus.Config;
using NServiceBus.Config.ConfigurationSource;
using NServiceBus.Logging;

public class ConfigureUnicastBus : IProvideConfiguration<UnicastBusConfig>
{
    readonly ILog Log = LogManager.GetLogger(typeof(ConfigureUnicastBus));
    public static string EndpointName;

    public UnicastBusConfig GetConfiguration()
    {
        //read from existing config 
        var config = (UnicastBusConfig)ConfigurationManager.GetSection(typeof(UnicastBusConfig).Name);

        if (config == null)
        {
            //create new config if it doesn't exist
            config = new UnicastBusConfig
            {
                MessageEndpointMappings = GenerateMappings()
            };
        }
        return config;
    }

    MessageEndpointMappingCollection GenerateMappings()
    {
        var mappings = new MessageEndpointMappingCollection();

        var messageType = typeof(GatedPublishRunner.Event);
        var endpoint = EndpointName;

        Log.InfoFormat("Mapping {0} to {1}", messageType, endpoint);

        mappings.Add(new MessageEndpointMapping
        {
            AssemblyName = messageType.Assembly.FullName,
            TypeFullName = messageType.FullName,
            Endpoint = endpoint
        });

        return mappings;
    }
}
```

## Packages
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="NServiceBus" version="6.0.0-beta0001" targetFramework="net452" allowedVersions="[6,7)"  />
  <package id="NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="7.0.0-alpha0359" targetFramework="net452" allowedVersions="[7,8)"  />
  <package id="WindowsAzure.ServiceBus" version="3.1.6" targetFramework="net452" />
</packages>
```

## Stacktrace
```
Unhandled Exception: System.InvalidOperationException: No publishers configured for `GatedPublishRunner+Event`
   at NServiceBus.AzureServiceBus.PublishersConfiguration.GetPublishersFor(Type type)
   at NServiceBus.AzureServiceBus.EndpointOrientedTopologySectionManager.DetermineTopicsFor(Type eventType)
   at NServiceBus.AzureServiceBus.EndpointOrientedTopologySectionManager.BuildSubscriptionHierarchy(Type eventType)
   at NServiceBus.AzureServiceBus.EndpointOrientedTopologySectionManager.DetermineResourcesToSubscribeTo(Type eventType)
   at NServiceBus.AzureServiceBus.SubscriptionManager.<Subscribe>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Features.AutoSubscribe.ApplySubscriptions.<OnStart>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Routing\AutomaticSubscriptions\AutoSubscribe.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Features.FeatureActivator.<StartFeatures>d__5.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.StartableEndpoint.<StartFeatures>d__4.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\StartableEndpoint.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.StartableEndpoint.<Start>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\StartableEndpoint.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Endpoint.<Start>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Endpoint.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BaseRunner.CreateEndpoint() in C:\Users\Ramon\src\particular\EndToEnd\src\PerformanceTests\Common.Data\Scenarios\BaseRunner.cs:line 146
   at BaseRunner.Execute(Permutation permutation, String endpointName) in C:\Users\Ramon\src\particular\EndToEnd\src\PerformanceTests\Common.Data\Scenarios\BaseRunner.cs:line 31
   at Host.Program.Main() in C:\Users\Ramon\src\particular\EndToEnd\src\PerformanceTests\Common.Data\Program.cs:line 52```

**Comment by andreasohlund** [comment]
Could it be an issue with `IProvideConfiguration` being called to late, does it work if you supply the mappings using the static api?

http://docs.particular.net/nservicebus/messaging/routing#unicast-routing-endpoint-mapping-layer

**Comment by ramonsmits** [comment]
@andreasohlund Don't know, it works for all the other transports so if it would be too late that other transports would have similar issues.

@timbussmann Is currently looking into creating a workaround using that approach

**Comment by weralabaj** [comment]
Can you decide if that should be part of https://github.com/Particular/PlatformDevelopment/issues/718? I see Ramon mentioned it there.

**Comment by yvesgoeleven** [comment]
This is not a bug, it's by design. @andreasohlund It was decided that the unicast routing api was for unicast transports only remember and the routing info would not be passed into the transport so that it could derive it's multicast settings from it. So, to my regret, @ramonsmits and our users will from now on have to specify it using the replacement API (PublisherNames) for the multicast part of the transport when the endpoint oriented topology is on.

**Comment by ramonsmits** [comment]
This is pretty weird. If this is the case atleast work on informing the user with helpfull validations as the current one really leaves you in the dark after upgrading.

**Comment by ramonsmits** [comment]
Shouldn't this be backwards compatible? A NServiceBus V5 ASB endpoint should be able to work with a NServiceBus V6 ASB endpoint.

**Comment by weralabaj** [comment]
@ramonsmits the info that you need to include this in configuration will be in the upgrade guide, will that address your concern? it's not created yet, but I added TODO item to remember about this specific case.

**Comment by andreasohlund** [comment]
>Shouldn't this be backwards compatible?

Pretty sure you have to specify the "legacy" topology?

**Comment by timbussmann** [comment]
> Shouldn't this be backwards compatible? A NServiceBus V5 ASB endpoint should be able to work with a NServiceBus V6 ASB endpoint.

it is if you use the "legacy" `EndpointOrientedTopology` which is currently selected by default.

As already discussed on slack, I think it would make sense to force the user to chose the apropriate topology ("v5LegacyTopology" for backward compat or the forwarding topology otherwise). If we do not force users and default to:
* legacy topology: sucks for new users since they need to map publishers which wouldn't be necessary with the new topology
* new topology: sucks for existing users because of broken backwards compatibility
