### ISSUE TITLE
System.ArgumentException: RuleName

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureServiceBus#270]
Getting the following exception:

> System.ArgumentException: RuleName 'GatedPublishRunner+Event' contains character(s) that are not allowed by Service Bus. Entity names or path can contain only letters, numbers, periods (.), hyphens (-), and underscores (_).

Based on the usage of **ValidateAndHashIfNeeded** I would not expect this exception.

Using the *V6Sanitization* snippet does not result in this exception likely to indicate that *ValidateAndHashIfNeeded* is broken.

The last NServiceBus code in the stacktrace is:

     at NServiceBus.AzureServiceBus.AzureServiceBusForwardingSubscriptionCreator.<Create>d__5.MoveNext()

Maybe the *sanitization* is not applied everywhere or maybe the sanitization is incorrect.

This is the initialization:

```c#
        endpointConfiguration
            .UseTransport<AzureServiceBusTransport>()
            .UseTopology<ForwardingTopology>()
            .ConnectionString(connectionstring)
            .Sanitization().UseStrategy<ValidateAndHashIfNeeded>();
```

## Packages

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="NServiceBus" version="6.0.0-beta0004" targetFramework="net452" />
  <package id="NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="7.0.0-beta0007" targetFramework="net452" />
  <package id="WindowsAzure.ServiceBus" version="3.3.0" targetFramework="net452" />
</packages>
``` 

## Stack trace
```
|FATAL|1|Host.Program|Main
System.ArgumentException: RuleName 'GatedPublishRunner+Event' contains character(s) that are not allowed by Service Bus. Entity names or path can contain only letters, numbers, periods (.), hyphens (-), and underscores (_).
Parameter name: RuleName TrackingId:3776a263-ce2c-4166-a4ac-ddfdfadc77a7_G23_G23_B28, SystemTracker:ramon-test:Topic:bundle-1|PerformanceTest, Timestamp:6/28/2016 9:56:50 AM ---> System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: RuleName 'GatedPublishRunner+Event' contains character(s) that are not allowed by Service Bus. Entity names or path can contain only letters, numbers, periods (.), hyphens (-), and underscores (_).
Parameter name: RuleName TrackingId:3776a263-ce2c-4166-a4ac-ddfdfadc77a7_G23_G23_B28, SystemTracker:ramon-test:Topic:bundle-1|PerformanceTest, Timestamp:6/28/2016 9:56:50 AM

Server stack trace: 
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.ThrowIfFaultMessage(Message wcfMessage)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.HandleMessageReceived(IAsyncResult result)

Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass8_1.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [2]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [3]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpTransactionalAsyncResult`1.<>c.<GetAsyncSteps>b__18_3(TIteratorAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [4]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpSubscriptionClient.OnEndAddRule(IAsyncResult result)
   --- End of inner exception stack trace ---

Server stack trace: 
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpSubscriptionClient.OnEndAddRule(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.OpenOnceManager.<>c__DisplayClass6_0.<Begin>b__0(IAsyncResult r, Boolean& output)
   at Microsoft.ServiceBus.Messaging.OpenOnceManager.OpenOnceManagerAsyncResult`1.OperationComplete(IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(IAsyncResult result)

Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.SubscriptionClient.EndAddRule(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.AzureServiceBus.AzureServiceBusForwardingSubscriptionCreator.<Create>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.AzureServiceBus.TopologyCreator.<Create>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.AzureServiceBus.SubscriptionManager.<Subscribe>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Features.AutoSubscribe.ApplySubscriptions.<OnStart>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Routing\AutomaticSubscriptions\AutoSubscribe.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Features.FeatureActivator.<StartFeatures>d__5.MoveNext() in C:\Build\src\NServiceBus.Core\Features\FeatureActivator.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.StartableEndpoint.<StartFeatures>d__4.MoveNext() in C:\Build\src\NServiceBus.Core\StartableEndpoint.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.StartableEndpoint.<Start>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\StartableEndpoint.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Endpoint.<Start>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Endpoint.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at BaseRunner.<CreateEndpoint>d__27.MoveNext() in S:\particular\EndToEnd\src\PerformanceTests\Common\Scenarios\BaseRunner.cs:line 230
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at BaseRunner.<Execute>d__21.MoveNext() in S:\particular\EndToEnd\src\PerformanceTests\Common\Scenarios\BaseRunner.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Host.Program.Main() in S:\particular\EndToEnd\src\PerformanceTests\Common\Program.cs:line 49
```

**Comment by yvesgoeleven** [comment]
The root of the problem:

setting ValidateAndHashIfNeeded does not change the default settings for validation & sanitization rules, for now they need to be specified using

var strategy = sanitization.UseStrategy<ValidateAndHashIfNeeded>();
strategy.QueuePathSanitization(queuePath => "sanitized queuePath");
strategy.TopicPathSanitization(topicPath => "sanitized topicPath");
strategy.SubscriptionNameSanitization(subscriptionName => "sanitized subscriptionName");
strategy.RuleNameSanitization(ruleName => "sanitized ruleName");
strategy.Hash(pathOrName => "hashed pathOrName");

I'll change the design so that calling UseStrategy also changes the defaults for these

**Comment by SeanFeldman** [comment]
Documentation on [`ValidateAndHashIfNeeded`](http://docs.particular.net/nservicebus/azure-service-bus/sanitization#automated-sanitization-versions-7-and-above) will need to be updated.

**Comment by ramonsmits** [comment]
@SeanFeldman @yvesgoeleven What is the status of this? The PR is merged so can this issue be closed? Also, neither this issue nor the PR has a milestone set. Is the release that contains this PR already pushed as a new beta to Nuget.org?

**Comment by yvesgoeleven** [comment]
@ramonsmits ValidateAndHashIfNeeded now properly sets the defaults, but you still need to set ValidateAndHashIfNeeded to get the behavior you want. This is indeed released as beta
