### ISSUE TITLE
Long running idle endpoints throw Messaging exceptions

### ISSUE THREAD

**Issue by jpv001** [Particular/NServiceBus.AzureServiceBus#305]
The endpoints were started on Friday morning and sat idle over the weekend. All of the endpoints in the screen shot have the same exception, some of them once, some twice and some not at all. The exception also occurred at different times for each endpoint, some on the Saturday, some on Monday

Seven of the thirteen endpoints threw the following exception at some point over the last 3 days. The endpoints themselves do not crash, they will still process messages and behave normally, they don't require a restart to operate normally following this exception.

**Versions (Latest beta of all):**
Autofac version=3.5.2
logentries.core version=2.8.0
logentries.nlog version=2.6.0
Microsoft.WindowsAzure.ConfigurationManager version=3.2.1
NLog version=4.3.7
NServiceBus version=6.0.0-beta0007
NServiceBus.Autofac version=6.0.0-beta0001
NServiceBus.Azure.Transports.WindowsAzureServiceBus version=7.0.0-beta0012
NServiceBus.RavenDB version=4.0.0-beta0007
OctoPack version=3.0.71
RavenDB.Client version=3.5.0-rc-35166
WindowsAzure.ServiceBus version=3.3.2

**Stack Trace:**
```
Fri Aug 19 09:09:29.1704 +00:00 2016 NServiceBus.StartableEndpoint Level: Debug, Started Main receiver
Fri Aug 19 09:09:29.1704 +00:00 2016 Gateway.Twilio.ConsoleEndpoint.Program+<MainAsync>d__1 Level: Info, Gateway.Twilio.ConsoleEndpoint started
Press any key to exit
Mon Aug 22 17:45:16.4591 +00:00 2016 NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier Level: Info, OptionsOnExceptionReceived invoked, 
	action: Receive, exception: Microsoft.ServiceBus.Messaging.MessagingException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 
	TrackingId:e8dedd50-4603-4e86-9190-fd15a06dfcc2_G25, Timestamp:8/22/2016 5:45:16 PM

 ---> System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: The service was unable to process the request; please retry the operation. 
 		For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:e8dedd50-4603-4e86-9190-fd15a06dfcc2_G25, Timestamp:8/22/2016 5:45:16 PM

Server stack trace:
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.ThrowIfFaultMessage(Message wcfMessage)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.HandleMessageReceived(IAsyncResult result)

Exception rethrown at [0]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass8_1.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [2]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [3]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.EndReceiveCommand(IAsyncResult result, IEnumerable`1& messages)
   --- End of inner exception stack trace ---

Server stack trace:
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.EndReceiveCommand(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.ReceiveAsyncResult.<>c.<GetAsyncSteps>b__12_3(ReceiveAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [0]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.OnEndTryReceive(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.<>c.<GetAsyncSteps>b__15_3(RetryReceiveAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.TryReceiveEnd(IAsyncResult r, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndTryReceive(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndReceive(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceivePump.PumpAsyncResult.<>c.<GetAsyncSteps>b__7_3(PumpAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Mon Aug 22 17:52:07.5956 +00:00 2016 NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier Level: Info, OptionsOnExceptionReceived invoked, action: Receive, exception: Microsoft.ServiceBus.Messaging.MessagingException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 3cbc29d6-aa28-42d7-9927-9e0064f9dca3_G25 --->
 System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 3cbc29d6-aa28-42d7-9927-9e0064f9dca3_G25

Server stack trace:
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.ThrowIfFaultMessage(Message wcfMessage)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.HandleMessageReceived(IAsyncResult result)

Exception rethrown at [0]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass8_1.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [2]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [3]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.EndReceiveCommand(IAsyncResult result, IEnumerable`1& messages)
   --- End of inner exception stack trace ---

Server stack trace:
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.EndReceiveCommand(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.ReceiveAsyncResult.<>c.<GetAsyncSteps>b__12_3(ReceiveAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [0]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.OnEndTryReceive(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.<>c.<GetAsyncSteps>b__15_3(RetryReceiveAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.TryReceiveEnd(IAsyncResult r, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndTryReceive(IAsyncResultresult, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndReceive(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceivePump.PumpAsyncResult.<>c.<GetAsyncSteps>b__7_3(PumpAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
```
This is a screenshot of the server showing the console windows of the endpoints, as can be seen 7/13 have the exception.

![endpoints crashing](https://cloud.githubusercontent.com/assets/1662796/17873352/7aea544c-6908-11e6-913e-5088fa6cba41.PNG)

**Comment by SeanFeldman** [comment]
@jpv001 could you please provide some extra information?

1. Did endpoints continue processing after this exception was logged?
1. Do all these endpoints utilise the same namespace or multiple namespaces?
  1 . What region(s) are you using for this test?

This is an internal Service Bus exception, but if endpoints did not shut down, that means endpoint could recover from the exception. We'll need as much information as possible to investigate further.

Thank you.

**Comment by jpv001** [comment]
1. The endpoints themselves do not crash, they will still process messages and behave normally, they don't require a restart to operate normally following this exception. The exception simply appears in the logs / on the console and the endpoint continues to behave normally.
2. All of these endpoints are in different namespaces.
3. We're using the Australia South East Azure region.

If you need anything else just let me know.

**Comment by yvesgoeleven** [comment]
@jpv001 the exception indicates that the ServiceBus service had some internal problems, there's not much we can do about it besides what we currently do (logging the problem, backing off a bit and then reconnect). Do you suggest that we should do something differently?

**Comment by jpv001** [comment]
As the endpoint still functions this isn't a critical issue, but rather an anomaly in the logs that should be reported upon to make sure it wasn't anything more serious, especially considering we're using the beta. I'm happy to close this if it's a known issue and there is little that can be done about it.

**Comment by yvesgoeleven** [comment]
@jpv001 in this case there is no real problem, it's just a temporary hickup in ASB itself. We log the entire exception, but the most important part is the tracking id so that you as a customer could use that to send to azure support in order to figure out what is going on when the problem would persist. Would it make more sense if we did not log the entire stacktrace, but only the section with the message & tracking id?

**Comment by jpv001** [comment]
I'm always in favour of providing more information with an exception rather than less, I think removing the stack trace may create some additional work when trying to trace down the issue through the solution. At least this way you can see where things went wrong and ask the right questions in the right repo, without the stack trace this would look like a core NSB failure rather than a ASB one. If the error could be made more apparent with regards to its messaging that would be ideal, however as this isn't a predictable thing I'm not sure we can reliably trap this error.

**Comment by yvesgoeleven** [comment]
@jpv001 we'll leave it as is then, the exception message comes from ASB it contains little information to determine client side what actually happened. I'll close the issue
