### ISSUE TITLE
Message processed multiple times when sending from a SendOnly endpoint

### ISSUE THREAD

**Issue by carlbm** [Particular/NServiceBus.AzureServiceBus#329]
When a message is sent from a send only endpoint the handler is invoked multiple times. There is no limit to the number of times the handler is invoked (the first line of the stack trace would suggest otherwise, but it's not the case), and it is invoked again immediately after it returns - I've only tested it with one message however, ignoring the immediate and delayed retry rules. 

Here's the stack trace:

`2016-09-16 11:55:12.849 WARN  NServiceBus.RecoverabilityExecutor Delayed Retry will reschedule message 'fd0fb6cd-b939-4882-9ceb-a68300c1ff8c' after a delay of 00:00:30 because of an exception:
System.ArgumentException: Entity address value can't be empty
Parameter name: value
   at NServiceBus.Transport.AzureServiceBus.EntityAddress..ctor(String value) in C:\Build\src\Transport\Topology\MetaModel\EntityAddress.cs:line 49
   at NServiceBus.Transport.AzureServiceBus.DefaultBatchedOperationsToBrokeredMessagesConverter.SetReplyToAddress(OutgoingMessage outgoingMessage, BrokeredMessage brokeredMessage, RuntimeNamespaceInfo destinationNamespace) in C:\Build\src\Transport\Sending\DefaultBatchedOperationsToBrokeredMessagesConverter.cs:line 64
   at NServiceBus.Transport.AzureServiceBus.DefaultBatchedOperationsToBrokeredMessagesConverter.Convert(BatchedOperation outgoingOperation, RoutingOptions routingOptions) in C:\Build\src\Transport\Sending\DefaultBatchedOperationsToBrokeredMessagesConverter.cs:line 36
   at NServiceBus.Transport.AzureServiceBus.DefaultBatchedOperationsToBrokeredMessagesConverter.<>c__DisplayClass2_0.<Convert>b__0(BatchedOperation x) in C:\Build\src\Transport\Sending\DefaultBatchedOperationsToBrokeredMessagesConverter.cs:line 23
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NServiceBus.Transport.AzureServiceBus.DefaultOutgoingBatchRouter.RouteBatch(Batch batch, BrokeredMessageReceiveContext context, DispatchConsistency consistency) in C:\Build\src\Transport\Sending\DefaultOutgoingBatchRouter.cs:line 79
   at NServiceBus.Transport.AzureServiceBus.DefaultOutgoingBatchRouter.RouteBatches(IEnumerable`1 outgoingBatches, ReceiveContext context, DispatchConsistency consistency) in C:\Build\src\Transport\Sending\DefaultOutgoingBatchRouter.cs:line 42
   at NServiceBus.Transport.AzureServiceBus.Dispatcher.<DispatchWithTransactionScopeIfRequired>d__4.MoveNext() in C:\Build\src\Transport\Seam\Dispatcher.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.Dispatcher.<DispatchAccordingToIsolationLevel>d__3.MoveNext() in C:\Build\src\Transport\Seam\Dispatcher.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\MainPipelineExecutor.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<ProcessMessageAsync>d__30.MoveNext() in C:\Build\src\Transport\Receiving\MessageReceiverNotifier.cs:line 194`

**Comment by yvesgoeleven** [comment]
@carlbm thank you for reporting this, I will look into it

**Comment by carlbm** [comment]
This is for RC2 btw, and was not an issue in beta 12

**Comment by yvesgoeleven** [comment]
Indeed, I can trace the problem back to my commit from 4 days ago https://github.com/Particular/NServiceBus.AzureServiceBus/commit/d627fc005e6c557b58056a43bbf8e02049df9209#diff-44dc3945b6f5e3209b43e0ceec050227R158

What happens in my opinion:
- the sender adds an empty reply to header to the message on the line above
- the receiver gets this message and sends something in response to it, which fails (not sure if this exception above is the cause for this as well, I suspect that another exception must occur at this point for the repeat process to kick in, can you confirm is there another exception happening on send?)
- processing is retried (FLR), processing keeps failing up to 5 times
- SLR is kicking in, which now fails on it's own, as it tries to delay send using an empty header, and causes more retries until the queue's max delivery count is reach and the original message is moved to the dead letter queue (eventually)

**Comment by SeanFeldman** [comment]
@carlbm we've released [NSB.ASB RC3](https://www.nuget.org/packages/NServiceBus.Azure.Transports.WindowsAzureServiceBus/7.0.0-rc0003). Please have a try to confirm it solves the issue for you.
