### ISSUE TITLE
ObjectDisposedException is thrown when shutting endpoint down

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureServiceBus#337]
## Who's affected

* Anyone using Azure Service Bus

## Symptoms

An exception `System.ObjectDisposedException` with message "Cannot access a disposed object." is thrown when endpoint is shutting down

## Original issue

Getting the following exception at endpoint shutdown with 7.0.0-rc0003, this doesnt seem to be happening with 7.0.0-beta0013

> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement+RedirectContainerChannelFactory`1[System.ServiceModel.Channels.IRequestSessionChannel]'.

I'm getting this primarily when using transaction modes None and Atomic.

<details>
  <summary>Show stacktrace</summary>
```
2016-09-21 10:51:01.6582|INFO|4|NServiceBus.Transport.AzureServiceBus.MessagePump|Messagepump stopped
2016-09-21 10:51:01.6582|FATAL|1|Host.Program|Main
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement+RedirectContainerChannelFactory`1[System.ServiceModel.Channels.IRequestSessionChannel]'.
Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposed()
   at System.ServiceModel.Channels.ChannelFactoryBase`1.ValidateCreateChannel()
   at System.ServiceModel.Channels.ChannelFactoryBase`1.InternalCreateChannel(EndpointAddress address, Uri via)
   at Microsoft.ServiceBus.Messaging.Channels.SharedChannel`1.CreateChannelAsyncResult.<GetAsyncSteps>d__6.MoveNext()
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.Start()
Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.SharedChannel`1.OnEndCreateInstance(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_1(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
Exception rethrown at [1]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
Exception rethrown at [2]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.AbandonPrefetchedMessagesCloseAbortAsyncResult.<>c.<GetAsyncSteps>b__2_3(AbandonPrefetchedMessagesCloseAbortAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
Exception rethrown at [3]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.OnEndClose(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.ClientEntity.EndClose(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<Stop>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.<StopNotifiersForAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.<Stop>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.<Stop>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiver.<Stop>d__6.MoveNext() in C:\Build\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RunningEndpointInstance.<>c.<<StopReceivers>b__8_0>d.MoveNext() in C:\Build\src\NServiceBus.Core\Unicast\RunningEndpointInstance.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RunningEndpointInstance.<Stop>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Unicast\RunningEndpointInstance.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BaseRunner.<Execute>d__30.MoveNext() in C:\Users\ramon\src\particular\EndToEnd\src\PerformanceTests\Common\Scenarios\BaseRunner.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Host.Program.Main() in C:\Users\ramon\src\particular\EndToEnd\src\PerformanceTests\Common\Program.cs:line 55
2016-09-21 10:51:01.6822|ERROR|1|UnhandledException|Cannot access a disposed object.
Object name: 'Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement+RedirectContainerChannelFactory`1[System.ServiceModel.Channels.IRequestSessionChannel]'.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement+RedirectContainerChannelFactory`1[System.ServiceModel.Channels.IRequestSessionChannel]'.
Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposed()
   at System.ServiceModel.Channels.ChannelFactoryBase`1.ValidateCreateChannel()
   at System.ServiceModel.Channels.ChannelFactoryBase`1.InternalCreateChannel(EndpointAddress address, Uri via)
   at Microsoft.ServiceBus.Messaging.Channels.SharedChannel`1.CreateChannelAsyncResult.<GetAsyncSteps>d__6.MoveNext()
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.Start()
Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.SharedChannel`1.OnEndCreateInstance(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_1(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
Exception rethrown at [1]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
Exception rethrown at [2]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.AbandonPrefetchedMessagesCloseAbortAsyncResult.<>c.<GetAsyncSteps>b__2_3(AbandonPrefetchedMessagesCloseAbortAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
Exception rethrown at [3]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.OnEndClose(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.ClientEntity.EndClose(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<Stop>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.<StopNotifiersForAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.<Stop>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.<Stop>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiver.<Stop>d__6.MoveNext() in C:\Build\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RunningEndpointInstance.<>c.<<StopReceivers>b__8_0>d.MoveNext() in C:\Build\src\NServiceBus.Core\Unicast\RunningEndpointInstance.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RunningEndpointInstance.<Stop>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Unicast\RunningEndpointInstance.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BaseRunner.<Execute>d__30.MoveNext() in C:\Users\ramon\src\particular\EndToEnd\src\PerformanceTests\Common\Scenarios\BaseRunner.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Host.Program.Main() in C:\Users\ramon\src\particular\EndToEnd\src\PerformanceTests\Common\Program.cs:line 70
```
</details>

**Update**: #376 is a discussion for the next version we'll have to address this.

**Comment by SeanFeldman** [comment]
@ramonsmits could you provide steps to repro this?

**Comment by ramonsmits** [comment]
@SeanFeldman Shutdown an endpoint while busy receiving/processing.

**Comment by ramonsmits** [comment]
@SeanFeldman and I confirmed that RC2 and RC1 have shutdown issues too although different exceptions.

RC1:
```
2016-09-21 21:17:38.7733|INFO|55|NServiceBus.Transport.AzureServiceBus.MessagePump|Messagepump stopped
2016-09-21 21:17:38.9704|INFO|57|NServiceBus.RecoverabilityExecutor|Immediate Retry is going to retry message 'f1f56ad7-2c29-4a44-9a7e-a688017fda06' because of an exception:
System.OperationCanceledException: This messaging entity has already been closed, aborted, or disposed.
   at Microsoft.ServiceBus.Messaging.ClientEntity.ThrowIfClosed()
   at Microsoft.ServiceBus.Messaging.MessageReceiver.BeginComplete(TrackingContext trackingContext, IEnumerable`1 lockTokens, TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.ServiceBus.Messaging.ReceiveContext.BeginComplete(TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.ServiceBus.Messaging.BrokeredMessage.BeginComplete(TimeSpan timeout, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at Microsoft.ServiceBus.Common.Parallel.TaskHelpers.CreateTask(Func`3 begin, Action`1 end, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<HandleCompletion>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<ProcessMessageAsync>d__30.MoveNext()
```

**Comment by ramonsmits** [comment]
While busy trying to write a response for #314 I noticed that this is more likely te happen when:

- Using SendsAtomicWithReceive
- Allow a large max concurrency and/or prefetch size

**Comment by SeanFeldman** [comment]
Could be resolved by #349

**Comment by ramonsmits** [comment]
Not resolved by RC5.

**Comment by SeanFeldman** [comment]
We've discussed this with @yvesgoeleven and are hesitating to catch the exception. When [`MessagePump.Stop()`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/70beff9c426036fe37c62869c3c5603a09787010/src/Transport/Seam/MessagePump.cs#L102) is called, we [stop all receivers](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/70beff9c426036fe37c62869c3c5603a09787010/src/Transport/Topology/TopologyOperator.cs#L53) and [close all factories](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/70beff9c426036fe37c62869c3c5603a09787010/src/Transport/Topology/TopologyOperator.cs#L57), awaiting for code completion and log that message pump is stopped. The exception takes place in ASB later, after the fact that message pump was stopped.

**Comment by ramonsmits** [comment]
@SeanFeldman I agree, if this is something the SDK goes we should not try to prevent this. However, it might be a good thing to then document this? Maybe even included the guidance to not restart an endpoint but to just create a new process as I think @yvesgoeleven calls the 'Azure way'.

**Comment by yvesgoeleven** [comment]
@ramonsmits that is indeed a good idea, document it instead of trying to fix it

**Comment by ramonsmits** [comment]
Testing 7.0.1, no ObjectDisposedException or NullReferenceException yet but do see the following exception during shutdown:

```
2016-10-13 18:00:18.1031|INFO|36|NServiceBus.Unicast.UnicastBus|Initiating shutdown.
2016-10-13 18:00:18.1031|INFO|36|NServiceBus.Transport.AzureServiceBus.MessagePump|Stopping messagepump
2016-10-13 18:00:18.1031|INFO|36|NServiceBus.Transport.AzureServiceBus.TopologyOperator|Stopping notifiers
2016-10-13 18:00:18.1031|INFO|36|NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier|Stopping notifier for PerformanceTest
2016-10-13 18:00:18.1031|INFO|36|NServiceBus.Transport.AzureServiceBus.MessagePump|Stopping messagepump
2016-10-13 18:00:18.1031|INFO|36|NServiceBus.Transport.AzureServiceBus.TopologyOperator|Stopping notifiers
2016-10-13 18:00:18.1216|INFO|36|NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier|Stopping notifier for PerformanceTest.Retries
2016-10-13 18:00:18.6306|INFO|21|NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier|Notifier for PerformanceTest.Retries stopped
2016-10-13 18:00:18.6306|INFO|21|NServiceBus.Transport.AzureServiceBus.TopologyOperator|Forcing messaging factories to close
2016-10-13 18:00:18.9702|INFO|44|NServiceBus.Transport.AzureServiceBus.MessagePump|Messagepump stopped
2016-10-13 18:00:18.9702|FATAL|1|Host.Program|Main
System.ArgumentException: The argument lockTokens is null or empty.
Parameter name: lockTokens
   at Microsoft.ServiceBus.Messaging.MessageReceiver.BeginComplete(TrackingContext trackingContext, IEnumerable`1 lockTokens, TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.<>c__DisplayClass97_0.<CompleteBatchAsync>b__0(AsyncCallback c, Object s)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at Microsoft.ServiceBus.Common.Parallel.TaskHelpers.CreateTask(Func`3 begin, Action`1 end, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverExtensions.<SafeCompleteBatchAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<>c__DisplayClass31_0.<<PerformBatchedCompletionTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<Stop>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.<StopNotifiersForAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.<Stop>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.<Stop>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiver.<Stop>d__6.MoveNext() in C:\Build\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RunningEndpointInstance.<>c.<<StopReceivers>b__8_0>d.MoveNext() in C:\Build\src\NServiceBus.Core\Unicast\RunningEndpointInstance.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RunningEndpointInstance.<Stop>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Unicast\RunningEndpointInstance.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BaseRunner.<Execute>d__30.MoveNext() in C:\Users\ramon\src\particular\EndToEnd\src\PerformanceTests\Common\Scenarios\BaseRunner.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Host.Program.Main() in C:\Users\ramon\src\particular\EndToEnd\src\PerformanceTests\Common\Program.cs:line 58
```

**Comment by SeanFeldman** [comment]
Argument exception is a different issue, #369 and fixed in PR #371.
`ObjectDisposedException` is being thrown in `messageReceiver.CloseAsync()` *after* code is awaited. Required more investigation.

**Comment by SeanFeldman** [comment]
The outcome of the discussion in #372 could potentially help with this issue as well.

**Comment by SeanFeldman** [comment]
We should try to repro this with native ASB only.

**Comment by SeanFeldman** [comment]
After a long session trying to chase the issue in ASB SDK with @bording, we found nothing wrong with the code. What became apparent, is that we had a design flaw in the transport - a set of factories was created for all the message pumps involved in an endpoint, and therefore factories were re-used. What happens is that `TopologyOperator` is closing receive notifiers _and_ factories. Since `TopologyOperator` does it invoked by *each individual `MessagePump`*, notifiers per message message pump are closed (OK), and shared factories are closed (NOT OK). 

Options to address is:

1. `AzureServiceBusTransport` (`TransportDefinition`) should override `Stop()` method and invoke stop operation for shared factories, not each message pump. That would require a change in the public API. A spike PR is here [TODO].
1. Wrap closing of factories with with try/catch in `TopologyOperator.Stop()`. This is not ideal, but is not a breaking change.

**Comment by ramonsmits** [comment]
Additional ObjectDisposedException at different location:

```
2016-10-17 09:19:02.6634|WARN|13|NServiceBus.Transport.AzureServiceBus.MessageReceiverExtensions|An object disposed exception occured while trying to complete a batch of messages, this might imply that the connection was lost or the underlying queue got removed, the exception was Cannot access a disposed object.
Object name: 'Microsoft.ServiceBus.Messaging.BatchManager`1[System.Guid]'.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.ServiceBus.Messaging.BatchManager`1[System.Guid]'.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at Microsoft.ServiceBus.Messaging.BatchManager`1.BeginBatchedOperation(TrackingContext trackingContext, IEnumerable`1 batchItems, TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.ServiceBus.Messaging.BatchManagerAsyncResult`1..ctor(TrackingContext trackingContext, BatchManager`1 batchManager, IEnumerable`1 msgs, TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.OnBeginComplete(TrackingContext trackingContext, IEnumerable`1 lockTokens, Boolean fromSync, TimeSpan timeout, AsyncCallback callback, Object asyncState)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryMessagesOperationAsyncResult.<>c.<GetAsyncSteps>b__19_5(RetryMessagesOperationAsyncResult thisPtr, KeyValuePair`2 lockTokenGroup, TimeSpan t, AsyncCallback c, Object s)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.ParallelAsyncResult`1..ctor(TIteratorAsyncResult iteratorAsyncResult, ICollection`1 workItems, BeginCall`1 beginCall, EndCall`1 endCall, TimeSpan timeout, AsyncCallback callback, Object state)

Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)

Exception rethrown at [1]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndCompleteBatch(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverExtensions.<SafeCompleteBatchAsync>d__1.MoveNext()
```

**Comment by ramonsmits** [comment]
It seems that that last exception results in shutdown to hang.
