### ISSUE TITLE
V6 multiple invocations of GetConfiguration<T> in NamingConventions.QueueNamingConvention()

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#339]
Origin: [GG post](https://groups.google.com/forum/#!topic/particularsoftware/fruKUEz6QbA)

ASB `QueueAndTopicByEndpointTopology` topology is using conventions to validate and sanitise entity paths/names. When `QueueNamingConvention` func is invoked, it's calling `settings.GetConfigSection<AzureServiceBusQueueConfig>()` each time.

<details>
<summary>From the GG post</summary>
We have implemented a custom configuration class (AzureServiceBusConfig) that implements IProvideConfiguration<AzureServiceBusQueueConfig>, INeedInitialization.  We've noticed that the GetConfiguration method is called repeatedly (see below for the stack trace) but we're not sure why it is being called more than once (at startup).

Basically, is this the expected behavior and if so, why is this called multiple times?  It seems like this should be cached after the first execution, but I can watch it in dbgview get called nearly non-stop.

-  stackTrace {
   at Not.Our.Actual.Namespace.AzureServiceBusConfig.GetConfiguration()
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.QueueAndTopicByEndpoint.NamingConventions.<>c.<.cctor>b__34_0(ReadOnlySettings settings, Type messagetype, String queueName, Boolean doNotIndividualize)
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.QueueAndTopicByEndpoint.NamingConventions.<>c.<.cctor>b__34_8(ReadOnlySettings settings, Address address, Boolean doNotIndividualize)
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.QueueAndTopicByEndpoint.QueueAndTopicByEndpointTopology.GetSender(Address original)
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusSender.SendInternal(TransportMessage message, SendOptions options, Boolean expectDelay)
   at ServiceControl.Plugin.ServiceControlBackend.Send(Object messageToSend, TimeSpan timeToBeReceived)
   at ServiceControl.Plugin.Nsb5.Heartbeat.Heartbeats.HeartbeatStartup.SendHeartbeatMessage(HostInformation hostInfo)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
} System.Diagnostics.StackTrace
</details>

**Comment by SeanFeldman** [comment]
This has been fixed in V7.

**Comment by ramonsmits** [comment]
I stumbled upon the same issue providing confiuratino via `IProvideConfiguration<AzureServiceBusQueueConfig>` and it seems to be called for every message received and/or send.

As this is not critical this can probably be closed as it is fixed in ASB V7?

**Comment by SeanFeldman** [comment]
Agreed.
