### ISSUE TITLE
Sending messages in batch throws a TransactionSizeExceededException

### ISSUE THREAD

**Issue by HEskandari** [Particular/NServiceBus.AzureServiceBus#347]
This is based on a case (00021184). Looks like we don't take message count when sending a batch. Here's the stack trace:

<details>
<summary>Exception details</summary>
2016-09-27 01:07:22.586 ERROR NServiceBus.Transport.AzureServiceBus.DefaultOutgoingBatchRouter Failed to dispatch a batch with the following message IDs: 20ba56ea-58c3-490e-aae0-c502cc3bc3f8, f192014c-b4eb-49bd-9047-7b119eb9c6c5, 0f9c9f9e-dfd8-4ad0-b501-0b26da6a6734, 25a0120d-1bab-493c-852e-4fe10299b12f, a57367f6-31a7-4f80-8e5f-e968513f4be3, 9316207e-796e-45ee-9f18-44af609f0caf, 3ad01ddc-5ab9-49ed-9986-fd22ecacc173, 83fac499-3be4-476f-96c5-7c1f5ef56fea, e0a0230f-5216-46ce-9663-de2736816def, 97b4b8b6-d62b-4d48-a596-1d9045dd2891, 7c41193d-3984-40bd-bb37-ca54a1e06028, 8f78444d-907b-4609-af5b-70d50bad822d, 94df6199-b818-4463-87c3-e3ec9b3f7f3a, 1b5548be-d1b0-4e2d-93e8-782fe8a943c0, a2143b10-c8d1-4e85-9906-38fe3fd0b7a8, 32203825-7be0-491a-ac81-c0f885bc9693, 5837be12-4741-4e15-b623-42056bbc0692, d4fe8286-c80e-4e18-9c2e-bddbacd92ef1, 197eb81d-d95a-42d0-af1c-f1a9c66ad929, 459648ad-aedc-49a0-9169-0962f0fd8188, 1537661d-01a8-42ba-acd0-bbc5c188d7c3, f00e0e60-75d2-49fc-9055-b7afac1fa033, 7ff478b6-c4d3-485e-9263-bfe8b324bab5, 5ab37fa8-4454-4d1e-a6de-5ff8555a2694, d6cc2970-64d9-4bf2-9df2-5531acdc2c89, e3f06795-f161-43b3-af48-c4388b78d0b0, 0465a20a-e27f-414a-983d-cf4eabdc3435, 6fdc616a-4f2a-44ce-b647-9f414d7fcd13, 9c616490-450c-4cda-8a49-9fa990786048, 38e8f19f-1533-4fb3-b878-4ad3488380f8, 896ea4e4-cbcd-4063-a8ad-23ff9f053dee, 69f1c31e-4176-464d-a8d1-4f275addc983, 9d422f8b-3841-40d0-9bae-c4532b9ea878, f0f0e86b-aeb6-4f25-9d84-971019c75dfa, 0c660ffe-f7c7-468d-9fb0-70e1004c5221, 468f7408-0cda-4bd7-bd8f-550e3e9fbc22, fda72735-a6d6-4cbe-8574-1aefa6cb94f5, 1b07d570-e66c-483c-a4ca-d60698da26eb, 2e893650-7f66-41ff-9ebd-b81d0ab2eeb1, 0260680c-143d-4ea5-a752-7b928021c604, 6c0d91a8-273e-4f8d-98e5-e68f3d10141c, fc765d58-4cb8-443c-9137-c1d7e58d0dd8, 7d1c2bee-5b36-4c89-a1ff-e82fa97af83a, b83be194-4fcb-4cbd-bd3b-159dcd5f2624, 95187bb1-722a-4f35-ab9f-e3b7152b61cd, b7b2f764-40ad-4520-bbe5-c17372e783ff, e9d3720f-cfd0-40f2-a669-076770828a64, 507c226d-1b8a-4b74-9c8e-96af6025e6a0, c2b220f4-be81-497e-a49f-70677f2e10aa, 494020a0-6e2a-4e75-91dd-9ac8a50e9f82, 889902a4-7f09-4903-9b65-21bae6e32dda, 5106d066-2f98-4eaa-8af3-03fdb9dd9e85, 98ea707b-5c7f-4d14-8570-0f9b8c1e6f72, 44f3e5c9-edde-4f81-ac91-c0da3187792b, e35c3547-f402-47f0-a046-16913fc34c8f, 415619f8-7ee1-424f-ae27-966af1b4f4a8, ecd2f135-7015-4640-b9ff-14a61c424c7f, 9c991a2d-e10d-4fcc-bb16-3ee49dc6b1ff, ffc91eb9-403a-4e42-bf4c-9f658bf9cfe1, 0ab5a5cc-9076-4595-a724-68d3b4f9165d, 9ed56bbc-6540-46ad-bfb3-6839ffd671f1, f1273653-78af-483b-8a50-a0236ca1abc3, 4a7eccd0-6416-440b-bfaa-037ddd6a550b, dc27aaa6-46c8-4026-8a15-e51921d4c67b, 15ae38ba-aeb2-4fc7-a578-2b3e2a253c94, e30de3dc-cf2a-4a76-b498-f2bbcece209f, dee22ef0-15a6-4753-910d-633f177d9ace, 73b1681c-646b-467d-860d-53d586b27f53, 4a194dfb-8396-4d12-9d13-36c7c4f0d2ed, 8f263520-d324-46ae-8d23-316eed1571d7, bd0255a8-4f83-4076-9142-cf1b7fb8089c, 0792c56d-1c4a-4823-8573-9577043a9cd1, 3a75e6dc-4186-4a6c-ae9f-ff34473dbb6a, 32b13aa6-e0f4-4197-8af3-e194c413ec77, 29d0fe16-b139-46ab-8c8e-09b5f56e4afd, fe802581-0dae-4fa3-a02b-2a05ee37e117, b16529de-fd11-46cc-8d8d-918ccc47d328, 35403b21-7697-4f0c-ac57-b98e1c6c5464, d9336190-78a2-4fe1-8276-95af7c11cb4e, 9411f9e9-52c8-4d46-8ca3-1ab44b277324, 805cce59-4eda-488d-aa70-dc023d422573, 2ff07067-f415-4603-bc84-9cec1eb17ac1, 4366c025-524b-4191-881c-d00655f2c3c4, a941e88c-c1e9-4ac9-ab84-e9f6d4e2833a, c73c3cb9-6893-4123-8443-a4cf7d95b616, 5d8951df-b6f0-4ff8-bb7f-95bcf3f40f4f, 7cafb246-ae36-46cb-9c08-dec1fab864ef, 0acac31e-da9b-4d35-b7e4-13a681581e49, 1ac07ca0-6536-4007-a3d4-a9d213df0b36, a3c39a5b-add1-4951-8ab7-00fd7c159fe5, 5bf90018-1214-4058-a730-a2da2b57d88f, 9563063d-e0bc-4d99-b496-3a9efdb36498, 746bc093-427a-495e-93ab-90231d7ce525, 2b0c299f-78cd-431a-bbf2-7aba027df5c3, 0af8b004-54b8-4e8d-b39b-69e474783061, 6bd4ade7-b409-43a4-abcf-f7d8f5042bbf, f8dde9d1-7455-44d6-9260-d3d4070e7f53, 6c73ff5c-0e7f-4fcc-a76d-4c7ec372152d, 7ca064df-4eea-4fea-8241-a1926774b3e1, 122d6a9d-fb16-4f43-a18e-473763638ec3, 4894dcb2-4897-45fa-990b-2498e7e29de6, 071502a0-7bc3-47e5-9e91-39336c232bce, 0f214564-d12a-40a5-a2b4-6df146e8007f, 661d53d9-a850-463c-80da-fdac885a8291, 741519ba-c0d9-4532-a46b-9d65704cd0cf, 298e7504-59de-4eea-9c89-716dd9635943, 1c34d504-7730-42f9-b008-35771ee391ed, 24df413c-f757-4a45-bbc4-96febc9706e0, b719f04b-145c-437b-a2e1-835f71c54002, d750fbc6-73f0-410a-ab50-44dfab554b59, 1b788486-86c6-4cc4-b10c-6b0374c72676, c3b6d83a-e8f8-45e7-a0e7-48bd6ccf5d1a, 85a428c1-6177-4be0-a58b-d7cab4ece131, e05849f1-cc4b-4814-9f31-b882b165c776, 0a54e6f7-d43e-407e-8e1a-0d4f1da76bce, c0720050-f2ae-4b92-a4d6-755d1d81a6ca, 3049c24a-e68c-4535-99ab-a2392737b4bc, 42624854-8b47-4d5d-8b40-603d04e4a737, a2d80ef3-bd98-442e-91ac-d8cac334b0d4, e235d41c-ab8f-4ecd-a130-f5a8588ffe64, f8302544-3b07-486b-9d42-3f27a3abcb87, 46b8de61-67ba-46ae-ad7a-a98177204055, 94b3fbb3-d237-4274-bac5-7f50d188777f, e5381231-2a4a-4b77-a056-8466ef69a983, e4cc825b-0ad5-4a66-887e-812e4898b961, 4309b9e5-fa72-4a67-911b-c8788b06825f, 64533c09-0ebc-4148-948a-a98984f86f97, e3d8a89b-15c0-47a6-b65b-9010eca17bad

Microsoft.ServiceBus.Messaging.TransactionSizeExceededException: Cannot send more than 100 messages in a single transaction. TrackingId:1ab6c22d-5538-42f8-92ff-89cc02732b30_G9_B10, SystemTracker:mailmaster-ns:Queue:mailmaster.processor.endpoint, Timestamp:9/27/2016 12:07:35 AM ---> System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Cannot send more than 100 messages in a single transaction. TrackingId:1ab6c22d-5538-42f8-92ff-89cc02732b30_G9_B10, SystemTracker:mailmaster-ns:Queue:mailmaster.processor.endpoint, Timestamp:9/27/2016 12:07:35 AM
Server stack trace:
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.ThrowIfFaultMessage(Message wcfMessage)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.HandleMessageReceived(IAsyncResult result)
Exception rethrown at [0]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
Exception rethrown at [1]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass8_1.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
Exception rethrown at [2]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
Exception rethrown at [3]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpTransactionalAsyncResult`1.<>c.<GetAsyncSteps>b__18_3(TIteratorAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
Exception rethrown at [4]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageSender.EndSendCommand(IAsyncResult result)
--- End of inner exception stack trace ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageSender.EndSendBatch(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TaskWithRetryExtensions.<RetryOnThrottleAsync>d__1.MoveNext() in C:\Build\src\Transport\Connectivity\TaskWithRetryExtensions.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.DefaultOutgoingBatchRouter.<RouteBatchWithEnforcedBatchSizeAsync>d__14.MoveNext() in C:\Build\src\Transport\Sending\DefaultOutgoingBatchRouter.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.DefaultOutgoingBatchRouter.<RouteOutBatchesWithFallbackAndLogExceptionsAsync>d__13.MoveNext() in C:\Build\src\Transport\Sending\DefaultOutgoingBatchRouter.cs:line 127
</details>

## Update

When messages are batched and send under a transaction scope (`ReceiveOnly` or `SendsAtomicWithReceive`) ASB does not allow more than 100 messages in total to be sent out. As a result of that, send operation will fail and the incoming message will be moved to the error queue. The exception (`Microsoft.ServiceBus.Messaging.TransactionSizeExceededException`) will have the following error:

> Cannot send more than 100 messages in a single transaction. TrackingId:2819f937-e5de-463b-867d-114bda51d85c_G47_B19, SystemTracker:[asb-namespace-name]:Queue:[queue-path], Timestamp:[date-time]

We don't control number of messages in a batch until messages are dispatched and batches are created based on according to Isolation Level first, and then later also based on the messages total size. Only then, if a batch contains messages that are less than an allowed maximum size _and_ number of messages is more than 100, operation will fail with exception.

The exception is well documented ([here](https://azure.microsoft.com/en-us/documentation/articles/service-bus-messaging-exceptions/)). We could update [NSB.ASB batching documentation ](https://docs.particular.net/nservicebus/azure-service-bus/batching) to cover this edge case.

@Particular/azure-service-bus-maintainers  any suggestions?

## PoA
- [x] Implement custom exception with some guiding error message
- [x] Update doco [PR #1964](https://github.com/Particular/docs.particular.net/pull/1964)

**Comment by SeanFeldman** [comment]
I have a strong suspicion this has to do with a namespace. Need to confirm.

**Comment by SeanFeldman** [comment]
When TransportTransactionMode is `SendsAtomicWithReceive`, ASB will not accept more than 100 operation in a single batch. @Particular/azure-service-bus-maintainers since we don't have control over batched operation coming from the handler, should we improve the exception or perform the check prior to making an attempt to send anything out?

**Comment by SeanFeldman** [comment]
Updated the general description with more details.

**Comment by SeanFeldman** [comment]
I have a PR to demonstrate the scenario: https://github.com/Particular/NServiceBus.AzureServiceBus/pull/348

**Comment by yvesgoeleven** [comment]
Best thing to do is to catch this exception,  provide some guidance to either lower the batch size or lower the transaction mode, then rethrow

**Comment by andreasohlund** [comment]
+1 to throw a better ex for now. Not sure if we can do anything from a core perspective in the future?

Ie not sure if the core checking some kind of `TransportDefinition.MaxSendBatchSize` value would be enough value compared to just give a better ex?

@Particular/sqlserver-transport-maintainers 
@Particular/rabbitmq-transport-maintainers 
@Particular/azure-storage-queues-maintainers 

do you have similar limitations? (pretty sure at that MSMQ will throw `InsufficientResources` at some point as well if you send to much cc @Particular/nservicebus-maintainers )

**Comment by carlbm** [comment]
Is there a way for me to set the batch size?

**Comment by yvesgoeleven** [comment]
@carlbm Batch size can be controlled by MaximumMessageSizeInKilobytes (not in number yet), but in my opinion individual batch size is not really the problem, the number of total messages sent in the transaction is too large, even splitting it in smaller batches will not remove that problem as the transaction will unite them again.

**Comment by bording** [comment]
> do you have similar limitations? 

@andreasohlund RabbitMQ doesn't have any batching capability at all, so we just send each message that comes in individually.

**Comment by tmasternak** [comment]
> do you have similar limitations?

@andreasohlund SqlServer is not doing any batching yet. The limit is around ~64 MB depending on configuration of sql instance https://msdn.microsoft.com/en-us/library/ms143432.aspx

**Comment by SeanFeldman** [comment]
Will be released with RC5

**Comment by tchelidze** [comment]
Can't we simply restrict the batch size to 100 whenever `SendsAtomicWithReceive` is enabled [here](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/master/src/Transport/Sending/OutgoingBatchRouter.cs#L198) ?

**Comment by SeanFeldman** [comment]
This transport is a legacy transport and only critical bug fixes will be applied.

> Can't we simply restrict the batch size to 100 whenever SendsAtomicWithReceive is enabled here ?

When messages are send from a handler with the default dispatch mode the transport is not involved until the handler is completed. Upon dispatching messages will be grouped and attempted. At that point there's arguably no value to throw a custom exception as the broker will throw one.

**Comment by SeanFeldman** [comment]
Regarding restriction - since the transport is not involved until the handler is done, we cannot restrict the number of messages sent out. Therefore short answer to your question is: it's not possible.

**Comment by danielmarbach** [comment]
@tchelidze you could probably achieve this within your endpoint code by adding a behavior into the dispatch pipeline phase
