### ISSUE TITLE
System.ArgumentException: The argument lockTokens is null or empty.

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#358]
2016-10-07 15:16:08.1789|INFO|12|BaseRunner|Starting...
2016-10-07 15:16:08.1789|INFO|12|BaseRunner|Started
2016-10-07 15:16:08.1789|INFO|12|BaseRunner|Run: 00:01:24.4130000, please press SPACE to continue after 
2016-10-07 15:17:32.6170|INFO|19|Statistics|ReceiveFirstLastDuration: -1.0 (s)
2016-10-07 15:17:32.6170|INFO|19|Statistics|NumberOfMessages: 0.0 (#)
2016-10-07 15:17:32.6170|INFO|19|Statistics|Throughput: 0.0 (msg/s)
2016-10-07 15:17:32.6170|INFO|19|Statistics|NumberOfRetries: 0.0 (#)
2016-10-07 15:17:32.6170|INFO|19|Statistics|TimeToFirstMessage: 256.8 (s)
2016-10-07 15:17:32.6300|INFO|19|Statistics|PrivateBytes-Min: 298596.0 (kb)
2016-10-07 15:17:32.6300|INFO|19|Statistics|PrivateBytes-Max: 1721084.0 (kb)
2016-10-07 15:17:32.6300|INFO|19|Statistics|PrivateBytes-Avg: 725451.8 (kb)
2016-10-07 15:17:32.6300|INFO|19|BaseRunner|SeedDurationFactor ratio: 0.00 (4,348.66/0.00)
2016-10-07 15:17:32.6300|INFO|19|BaseRunner|Writing SeedDurationFactor ratio to 'C:\Users\ramon\AppData\Roaming\Perftests\Performance\Transaction Modes\ReceiveRunner\V6;Default;x64;Server;AzureServiceBus;InMemory;Json;Tiny;Outbox Off;Off;Receive;Audit Off;EnvCores256x;NoScaleOut\SeedDurationFactor.txt'.
2016-10-07 15:17:32.6461|INFO|19|BaseRunner|Stopping...
2016-10-07 15:17:32.6461|INFO|19|BaseRunner|Draining queue...
2016-10-07 15:17:34.1641|INFO|47|BaseRunner|Drained 0 message(s) in 0ms
2016-10-07 15:17:34.1641|INFO|47|BaseRunner|Stopped
2016-10-07 15:17:34.1641|INFO|47|NServiceBus.Unicast.UnicastBus|Initiating shutdown.
2016-10-07 15:17:34.1641|INFO|47|NServiceBus.Transport.AzureServiceBus.MessagePump|Stopping messagepump
2016-10-07 15:17:34.1641|INFO|47|NServiceBus.Transport.AzureServiceBus.TopologyOperator|Stopping notifiers
2016-10-07 15:17:34.1766|INFO|47|NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier|Stopping notifier for PerformanceTest
2016-10-07 15:17:34.1766|INFO|47|NServiceBus.Transport.AzureServiceBus.MessagePump|Stopping messagepump
2016-10-07 15:17:34.1766|INFO|47|NServiceBus.Transport.AzureServiceBus.TopologyOperator|Stopping notifiers
2016-10-07 15:17:34.1766|INFO|47|NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier|Stopping notifier for PerformanceTest.Retries
2016-10-07 15:17:34.5363|INFO|57|NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier|Notifier for PerformanceTest.Retries stopped
2016-10-07 15:17:34.5363|INFO|57|NServiceBus.Transport.AzureServiceBus.TopologyOperator|Forcing messaging factories to close
2016-10-07 15:17:35.8020|INFO|57|NServiceBus.Transport.AzureServiceBus.MessagePump|Messagepump stopped
2016-10-07 15:17:35.8020|FATAL|1|Host.Program|Main
System.ArgumentException: The argument lockTokens is null or empty.
Parameter name: lockTokens
   at Microsoft.ServiceBus.Messaging.MessageReceiver.BeginComplete(TrackingContext trackingContext, IEnumerable`1 lockTokens, TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.<>c__DisplayClass97_0.<CompleteBatchAsync>b__0(AsyncCallback c, Object s)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at Microsoft.ServiceBus.Common.Parallel.TaskHelpers.CreateTask(Func`3 begin, Action`1 end, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverExtensions.<SafeCompleteBatchAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<>c__DisplayClass31_0.<<PerformBatchedCompletionTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<Stop>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.<StopNotifiersForAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.<Stop>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.<Stop>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiver.<Stop>d__6.MoveNext() in C:\Build\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RunningEndpointInstance.<>c.<<StopReceivers>b__8_0>d.MoveNext() in C:\Build\src\NServiceBus.Core\Unicast\RunningEndpointInstance.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RunningEndpointInstance.<Stop>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Unicast\RunningEndpointInstance.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at BaseRunner.<Execute>d__37.MoveNext() in C:\Users\ramon\src\particular\EndToEnd\src\PerformanceTests\Common\Scenarios\BaseRunner.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Host.Program.Main() in C:\Users\ramon\src\particular\EndToEnd\src\PerformanceTests\Common\Program.cs:line 58
2016-10-07 15:17:35.8246|ERROR|1|UnhandledException|The argument lockTokens is null or empty.

**Comment by SeanFeldman** [comment]
Addressed by #369
