### ISSUE TITLE
NumberOfClientsPerEntity cannot be set to value higher then 64

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureServiceBus#361]
I tried to call `transport.NumberOfClientsPerEntity(80);` and got the following exception. I tried to see what the max possible value is and that is 64.

As the exception messages talks about " The specified value (0) is invalid." it probably results in some kind of overflow.

```
2016-10-10 09:45:53.5800|FATAL|13|NServiceBus.StartableEndpoint|Receiver Main failed to start.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: The specified value (0) is invalid. "maxConcurrentCalls" must be greater than zero.
   at Microsoft.ServiceBus.Messaging.OnMessageOptions.set_MaxConcurrentCalls(Int32 value)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.Initialize(EntityInfo entity, Func`3 callback, Func`2 errorCallback, Func`2 processingFailureCallback, Int32 maximumConcurrency)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.<>c__DisplayClass18_0.<StartNotifiersFor>b__0(EntityInfo e)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.StartNotifiersFor(IEnumerable`1 entities)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.Start(TopologySection topologySection, Int32 maximumConcurrency)
   at NServiceBus.TransportReceiver.Start() in C:\Build\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 47
   at NServiceBus.StartableEndpoint.StartReceivers(List`1 receivers) in C:\Build\src\NServiceBus.Core\StartableEndpoint.cs:line 85
```

**Comment by SeanFeldman** [comment]
@ramonsmits what was the total concurrency limit? I suspect it's related to https://github.com/Particular/NServiceBus.AzureServiceBus/pull/357

**Comment by ramonsmits** [comment]
@SeanFeldman max concurrency was 32 (4 *8 logical processors)

**Comment by yvesgoeleven** [comment]
@ramonsmits I'm not seeing this on https://github.com/Particular/NServiceBus.AzureServiceBus/pull/357, so I assume its's the same issue
