### ISSUE TITLE
The given key (AzureServiceBus.Connectivity.MessageReceivers.PrefetchCount) was not present

### ISSUE THREAD

**Issue by ottarhenanger** [Particular/NServiceBus.AzureServiceBus#367]
Hi,
I've upgraded to version 7.0.0 (Release) of NServiceBus.Azure.Transports.WindowsAzureServiceBus.

Endpoint is configured as following:

  var transport = config.UseTransport<AzureServiceBusTransport>();
  transport.ConnectionString(serviceBusConnectionString);
  transport.UseTopology<ForwardingTopology>();
  transport.Sanitization().UseStrategy<Sha1Sanitization>();

Endpoint fail to start with the exception below.

2016-10-13 09:38:10.862 ERROR NServiceBus.StartableEndpoint Receiver Main failed to start.
System.Collections.Generic.KeyNotFoundException: The given key (AzureServiceBus.Connectivity.MessageReceivers.PrefetchCount) was not present in the dictionary.
   at NServiceBus.Settings.SettingsHolder.Get(String key) in C:\Build\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 94
   at NServiceBus.Settings.SettingsHolder.Get[T](String key) in C:\Build\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 20
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverCreator.<Create>d__3.MoveNext() in C:\Build\src\Transport\Connectivity\MessageReceiverCreator.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverLifeCycleManager.<>c__DisplayClass4_0.<Get>b__0(String s) in C:\Build\src\Transport\Connectivity\MessageReceiverLifeCycleManager.cs:line 22
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverLifeCycleManager.Get(String entityPath, String namespaceAlias) in C:\Build\src\Transport\Connectivity\MessageReceiverLifeCycleManager.cs:line 20
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.Start() in C:\Build\src\Transport\Receiving\MessageReceiverNotifier.cs:line 114
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.StartNotifiersFor(IEnumerable`1 entities) in C:\Build\src\Transport\Topology\TopologyOperator.cs:line 108
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.Start(TopologySection topologySection, Int32 maximumConcurrency) in C:\Build\src\Transport\Topology\TopologyOperator.cs:line 41
   at NServiceBus.TransportReceiver.Start() in C:\Build\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 47
   at NServiceBus.StartableEndpoint.StartReceivers(List`1 receivers) in C:\Build\src\NServiceBus.Core\StartableEndpoint.cs:line 85

**Comment by SeanFeldman** [comment]
@ottarhenanger any chance to provide a repro for this issue?

**Comment by yvesgoeleven** [comment]
This is very weird, we do set a default value for this key

**Comment by ottarhenanger** [comment]
Hi, I try to recreate the problem with an minimum project.

**Comment by SeanFeldman** [comment]
@ottarhenanger I've tried to repro this issue, and couldn't. See my spike [here](https://github.com/SeanFeldman/Sample.ASP.Net.WebApi.With.NSB.ASB).

**Comment by SeanFeldman** [comment]
Same issue as #368. Closing as a duplicate.
