### ISSUE TITLE
LockTokens is null or empty exception on endpoint shutdown

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#369]
## Who's affected

Anyone using Azure Service Bus transport version 7.0.1

## Symptoms

`NullReferenceException` exception with message "The argument lockTokens is null or empty" thrown during shutdown:

<details>
<summary>Exception details</summary>
2016-10-13 18:00:18.1031|INFO|36|NServiceBus.Unicast.UnicastBus|Initiating shutdown.
2016-10-13 18:00:18.1031|INFO|36|NServiceBus.Transport.AzureServiceBus.MessagePump|Stopping messagepump
2016-10-13 18:00:18.1031|INFO|36|NServiceBus.Transport.AzureServiceBus.TopologyOperator|Stopping notifiers
2016-10-13 18:00:18.1031|INFO|36|NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier|Stopping notifier for PerformanceTest
2016-10-13 18:00:18.1031|INFO|36|NServiceBus.Transport.AzureServiceBus.MessagePump|Stopping messagepump
2016-10-13 18:00:18.1031|INFO|36|NServiceBus.Transport.AzureServiceBus.TopologyOperator|Stopping notifiers
2016-10-13 18:00:18.1216|INFO|36|NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier|Stopping notifier for PerformanceTest.Retries
2016-10-13 18:00:18.6306|INFO|21|NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier|Notifier for PerformanceTest.Retries stopped
2016-10-13 18:00:18.6306|INFO|21|NServiceBus.Transport.AzureServiceBus.TopologyOperator|Forcing messaging factories to close
2016-10-13 18:00:18.9702|INFO|44|NServiceBus.Transport.AzureServiceBus.MessagePump|Messagepump stopped
2016-10-13 18:00:18.9702|FATAL|1|Host.Program|Main
System.ArgumentException: The argument lockTokens is null or empty.
Parameter name: lockTokens
   at Microsoft.ServiceBus.Messaging.MessageReceiver.BeginComplete(TrackingContext trackingContext, IEnumerable`1 lockTokens, TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.<>c__DisplayClass97_0.<CompleteBatchAsync>b__0(AsyncCallback c, Object s)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at Microsoft.ServiceBus.Common.Parallel.TaskHelpers.CreateTask(Func`3 begin, Action`1 end, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverExtensions.<SafeCompleteBatchAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<>c__DisplayClass31_0.<<PerformBatchedCompletionTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<Stop>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.<StopNotifiersForAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.<Stop>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.<Stop>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiver.<Stop>d__6.MoveNext() in C:\Build\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RunningEndpointInstance.<>c.<<StopReceivers>b__8_0>d.MoveNext() in C:\Build\src\NServiceBus.Core\Unicast\RunningEndpointInstance.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RunningEndpointInstance.<Stop>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Unicast\RunningEndpointInstance.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BaseRunner.<Execute>d__30.MoveNext() in C:\Users\ramon\src\particular\EndToEnd\src\PerformanceTests\Common\Scenarios\BaseRunner.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Host.Program.Main() in C:\Users\ramon\src\particular\EndToEnd\src\PerformanceTests\Common\Program.cs:line 58
</details>

## Description

When endpoint is stopping, last completion batch was performed if concurrent collection of lock tokens was not not empy. If two or more completion tasks where executing the check and getting positive result (ie collection is not empty), all tasks would attempt to acquire lock tokens for a concurrent stack and perform batch completion. If tokens are all consumed by one of the these tasks, then collection is empty and attempt to complete would throw an exception.

The new implementation addresses this by double check. First, checking if concurrent collection of lock tokens is not empty. If not empty, then it gets the tokens and checks if there are any tokens to be completed to ensure no other competing completion task has already acted on the tokes that were available. Only if there are token to complete, batched completion will be invoked.

## Additional changes

- Lock tokens local `buffer` is no longer cleared. Operation is not needed since number of locks (`count`) is known and only that number of items from buffer is used.
- Popping operation from `ConcurrentStack` is providing starting index and number of max elements to pop, which is `buffer.Length`.

**Comment by SeanFeldman** [comment]
@ramonsmits has identified the issue and was able to verify the fix as well.
