### ISSUE TITLE
Using AMQP results in MessageLockLostException

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureServiceBus#379]
## Who's affected

*  Anyone using Azure Service Bus with AMQP (transport type)

## Symptoms

* `MessageLockLostException` and `NullReferenceException` are thrown during endpoint shutdown

## Original issue

Configuring ASB to use AMQP with transaction mode ReceiveOnly results in a `MessageLockLostException`.

```
2016-10-17 09:01:40.4613|WARN|33|NServiceBus.Transport.AzureServiceBus.MessageReceiverExtensions|A message lock lost exception occured while trying to complete a batch of messages, you may consider to increase the lock duration or reduce the batch size, the exception was The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.
Microsoft.ServiceBus.Messaging.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndCompleteBatch(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverExtensions.<SafeCompleteBatchAsync>d__1.MoveNext()
```

Besides this I got an `NullReferenceException` at endpoint shutdown

```
2016-10-17 09:02:14.0450|WARN|13|SessionExtensions|CloseWithSuppress (System.NullReferenceException): Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<Stop>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.<StopNotifiersForAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.TopologyOperator.<Stop>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.<Stop>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiver.<Stop>d__6.MoveNext() in C:\Build\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RunningEndpointInstance.<>c.<<StopReceivers>b__8_0>d.MoveNext() in C:\Build\src\NServiceBus.Core\Unicast\RunningEndpointInstance.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.RunningEndpointInstance.<Stop>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Unicast\RunningEndpointInstance.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SessionExtensions.<CloseWithSuppress>d__1.MoveNext() in C:\Users\ramon\src\particular\EndToEnd\src\PerformanceTests\Utils\SessionExtensions.cs:line 13
```

**Comment by yvesgoeleven** [comment]
It seems to start whenever a second receiver is used transportConfiguration.NumberOfClientsPerEntity(2);, it works when transportConfiguration.NumberOfClientsPerEntity(1);

**Comment by danielmarbach** [comment]
@ramonsmits the null reference exception is probably caused due to the race on the list of internal receivers. `list.Add` is not thread safe. See https://github.com/Particular/NServiceBus.AzureServiceBus/pull/380/commits/c7be45df3d2a26e08636013b80ee62aea12fbcf2

**Comment by danielmarbach** [comment]
Raise https://github.com/Particular/NServiceBus.AzureServiceBus/issues/381

**Comment by yvesgoeleven** [comment]
@ramonsmits found the issue, there is a behavioral difference between SBMP & AMQP, receiver that completes a batch must be the same as the one that received a lock token for AMQP (not so for SBMP).

I repro'ed it using folllowing console app: It will work for TransportType NetMessaging but not for AMQP

 `var manager = NamespaceManager.CreateFromConnectionString("xxx");
var factorySettings = new MessagingFactorySettings
 {
                TokenProvider = manager.Settings.TokenProvider,
                TransportType = TransportType.Amqp
 };
 var factory = MessagingFactory.Create(manager.Address, factorySettings);

var receiver1 = factory.CreateMessageReceiver("myqueue", ReceiveMode.PeekLock);
var receiver2 = factory.CreateMessageReceiver("myqueue", ReceiveMode.PeekLock);

var message = receiver1.Receive();

receiver2.Complete(message.LockToken);

Console.WriteLine("Done");
Console.ReadLine();
`

**Comment by danielmarbach** [comment]
I assume batch completion still works if it is the same receiver?

So

```
var message1 = receiver1.Receive();
var message2 = receiver1.Receive();

receiver1.Complete(message1.LockToken, message2.LockToken);
```

would work?

**Comment by yvesgoeleven** [comment]
@danielmarbach yes, I verified that

**Comment by SeanFeldman** [comment]
@ramonsmits please update issue description with the [required sections](https://github.com/Particular/PlatformDevelopment/blob/master/guidelines/release-notes.md#bugs). Many thanks for raising it 😃
