### ISSUE TITLE
Problem connecting to Azure Service Bus

### ISSUE THREAD

**Issue by imperugo** [Particular/NServiceBus.AzureServiceBus#38]
Hi, 
I've updated an old application from NServicebus 4.something (don't remember) to the latest nuget package.

Now, starting the application I've a strange problem with the bus connection.

```
2015-06-01 14:25:40.334 +00:00 [Information] Going to create topology for address 'myqueue-io-distributor.error' if needed
2015-06-01 14:25:40.338 +00:00 [Information] Going to create queue for address 'myqueue-io-distributor.error' if needed
2015-06-01 14:25:40.391 +00:00 [Information] Checking existence cache for 'myqueue-io-distributor'
2015-06-01 14:25:40.393 +00:00 [Information] Checking namespace for existance of the queue 'myqueue-io-distributor'
```
after few minutes I get this error

```csharp
{"The token provider was unable to provide a security token while accessing 'https://mynamespace-sb.accesscontrol.windows.net/WRAPv0.9/'. Token provider returned message: 'The remote name could not be resolved: 'mynamespace-sb.accesscontrol.windows.net''."}

Server stack trace: 
   at Microsoft.ServiceBus.TokenProviderHelper.ThrowException(Uri requestUri, WebException exception)
   at Microsoft.ServiceBus.TokenProviderHelper.GetAccessTokenCore(Uri requestUri, String appliesTo, String requestToken, String simpleAuthAssertionFormat, TimeSpan timeout, String& expiresIn, String& audience)
   at Microsoft.ServiceBus.TokenProviderHelper.GetHttpAuthAccessTokenByAssertion(Uri requestUri, String appliesTo, String requestToken, String simpleAuthAssertionFormat, TimeSpan timeout)
   at Microsoft.ServiceBus.SharedSecretTokenProvider.OnBeginGetWebToken(String appliesTo, String action, TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.ServiceBus.TokenProvider.GetWebTokenAsyncResult.<get_GetTokenBeginCall>b__1e(GetWebTokenAsyncResult thisPtr, TimeSpan t, AsyncCallback c, Object s)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)

Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.ExceptionDispatcher.Throw(Exception exception)
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.TokenProvider.EndGetWebToken(IAsyncResult result)
   at Microsoft.ServiceBus.TokenProviderUtility.GetMessagingWebToken(TokenProvider tokenProvider, Uri namespaceAddress, String appliesTo, String action, Boolean bypassCache, TimeSpan timeout)
```

Of curse the connection string, issuer, etc are fine.
What's the problem?

Moreover seems that the NServiceBus.Azure.Transports.WindowsAzureServiceBus is using an old version of Microsoft.WindowsAzure.ConfigurationManager.

Any Hint?

**Comment by SeanFeldman** [comment]
@imperugo could you please provide  nuget package(s) names and versions your solution is using?
Thank you.

**Comment by imperugo** [comment]
I found the issue.
The old code was doing this:

```
new AzureServiceBusQueueConfig()
				{
					IssuerKey = "mykey",
					IssuerName = "owner",
					ServiceNamespace = "mynamespace",
					QueueName = Constants.QueueNames.DistributorQueue,
					ConnectionString = this.configuration.Bus.TransportConnectionString,
				}
```

if I comment IssuerKey, IssuerName and ServiceNamespace it works.
Probably the latest Nuget package managers these property differently.

**Comment by SeanFeldman** [comment]
@imperugo, I've noticed you're overriding `QueueName` - that one is obsoleted and it is recommended to use busConfiguration.EndpointName("name") instead. Doco: http://docs.particular.net/nservicebus/azure/azure-servicebus-transport#configuring-in-detail

**Comment by imperugo** [comment]
yeah, the code is based on an old version of NServiceBus, need to clean it
