### ISSUE TITLE
NullReferenceException in MessagePump.cs:line 57 when using AddSatelliteReceiver

### ISSUE THREAD

**Issue by agiudici1** [Particular/NServiceBus.AzureServiceBus#480]
## Who's affected

Anyone using Azure Service Bus transport and requires custom satellites.

## Symptoms

Endpoint cannot process messages and throws `NullReferenceException` exception when a custom satellite is added with a queue name that doesn't follow NServiceBus satellite queue naming convention.

## Original issue

When an endpoint adds a SatelliteReceiver (using the FeatureConfigurationContext.AddSatelliteReceiver), the standarnd handlers (the ones that implements IHandleMessages<T>) stop working, throwing the following exception:

2017-01-24 10:43:08.733 ERROR NServiceBus.RecoverabilityExecutor Moving message '933df19a-8781-41e6-808c-a70500e1eda7' to the error queue 'error' because processing failed due to an exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.Transport.AzureServiceBus.MessagePump.<<Init>b__3_1>d.MoveNext() in C:\Users\agiudici\Downloads\NServiceBus.AzureServiceBus-7.1.1\NServiceBus.AzureServiceBus-7.1.1\src\Transport\Seam\MessagePump.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<ProcessMessage>d__13.MoveNext() in C:\Users\agiudici\Downloads\NServiceBus.AzureServiceBus-7.1.1\NServiceBus.AzureServiceBus-7.1.1\src\Transport\Receiving\MessageReceiverNotifier.cs:line 225

It seems that MessagePump.Start method does not get called, at least not for the instance responsible for the handlers, and the variable named **throttler** is never initialized.

Steps to reproduce:
- Add a class that implements IHandleMessages<T>
- Add a Feature with a SatelliteReceiver listening on another queue. The Feature must be enabled.
- Send messages to both queues
- The messages of the main endpoint queue should fail with the above exception
- When the feature with the SatelliteReceiver is disabled, there are no errors and the handlers work ok.

Packages:
- NServiceBus v6.1.2
- NServiceBus.Azure.Transports.WindowsAzureServiceBus v7.1.1

**Comment by yvesgoeleven** [comment]
@agiudici1 thank you for reporting this, we'll look into it

**Comment by yvesgoeleven** [comment]
Root cause: Currently the association between the sattelite processing pipeline and the sattelite receive infrastructure is performed based on queue naming conventions (assuming core would prefix it), but using AddSatelliteReceiver any name can be provided. This causes the wrong pipeline to be associated with the sattelite receiver.

Solution: https://github.com/Particular/NServiceBus.AzureServiceBus/pull/483 is to flip the convention around in order to detect the mainqueue instead of the satellite queue.

Side effect: the instance specific queue (if enabled) will also get it's own operator now, but that should be fine as core is assuming this anyway

**Comment by SeanFeldman** [comment]
@agiudici1 also, you potentially try to work with a satellite queue that follows the NSB convention by building the queue transport address in the way described ([here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs#L67-L68)). If you need a custom queue name, this workaround won't work.
