### ISSUE TITLE
QuotaExceededException occurs and takes down endpoint

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.AzureServiceBus#501]
Currently 6 endpoints are set on the same namespace in Azure Service Bus. One endpoint went down last night.

No significant increase in behavior on the message bus at that time, the opposite actually, nothing was going on besides for each endpoint 1 heartbeat message a minute, this was our staging environment that no one was using at the point, confirmed by our application logs.

This seems to suggest that somewhere in the transport or our own code there is somehow a connection leak? We're using NSB5 for this product (still).

Given that it is pretty hard to get any kind of metrics out of the bus, I was wondering if this is seen before, if there is a way to get metrics out of the bus to look who the culprit of this connection increase could be.

**Comment by SeanFeldman** [comment]
Could you please provide a full stack trace?
`QuotaExceededException` usually would indicate that entity has reached its maximum capacity. Could you review the namespace and see if there are queues that reached the maximum size?

**Comment by janpieterz** [comment]
Sure thing! It is a connection quota exceeded, but to be sure I've verified all queues and topics to be empty, including no dead lettered ones.

Below the stack traces (there were multiple). Interestingly, it started with a timeout exception:
```
2017-03-01 22:15:54 (NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueSender) [Warning] TimeoutException occured when sending to queue Gateway
System.TimeoutException: The request operation did not complete within the allotted timeout of 00:01:10. The time allotted to this operation may have been a portion of a longer timeout. TrackingId:130d0089-f233-47f4-8c70-23a292756b98, Timestamp:3/1/2017 10:15:54 PM

Server stack trace: 


Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.DuplexCorrelationAsyncResult.End(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass17.<GetAsyncSteps>b__a(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [2]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [3]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpTransactionalAsyncResult`1.<GetAsyncSteps>b__35(TIteratorAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [4]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageSender.EndSendCommand(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageSender.OnEndSend(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [5]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.RunSynchronously()
   at Microsoft.ServiceBus.Messaging.MessageSender.Send(TrackingContext trackingContext, IEnumerable`1 messages, TimeSpan timeout)
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueSender.Send(BrokeredMessage brokeredMessage) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\AzureServiceBusQueueSender.cs:line 30
```


```
2017-03-01 22:21:14 (NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueSender) [Fatal] Non transient QuotaExceededException occured when sending to queue Gateway
Microsoft.ServiceBus.Messaging.QuotaExceededException: ConnectionsQuotaExceeded for namespace xxx. 276167e3-39ca-49a7-9c7b-0fdd008fe29b_G47 ---> System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: ConnectionsQuotaExceeded for namespace xxx. 276167e3-39ca-49a7-9c7b-0fdd008fe29b_G47

Server stack trace: 
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.ThrowIfFaultMessage(Message wcfMessage)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.HandleMessageReceived(IAsyncResult result)

Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.DuplexCorrelationAsyncResult.End(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass17.<GetAsyncSteps>b__a(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [2]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [3]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpTransactionalAsyncResult`1.<GetAsyncSteps>b__35(TIteratorAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [4]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageSender.EndSendCommand(IAsyncResult result)
   --- End of inner exception stack trace ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.RunSynchronously()
   at Microsoft.ServiceBus.Messaging.MessageSender.Send(TrackingContext trackingContext, IEnumerable`1 messages, TimeSpan timeout)
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueSender.Send(BrokeredMessage brokeredMessage) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\AzureServiceBusQueueSender.cs:line 30
```

```
2017-03-01 22:21:14 (NServiceBus.Azure.Transports.WindowsAzureServiceBus.SendResourceManager) [Fatal] A fatal exception occured while trying to send a message, the exception was ConnectionsQuotaExceeded for namespace xxx. 276167e3-39ca-49a7-9c7b-0fdd008fe29b_G47
Microsoft.ServiceBus.Messaging.QuotaExceededException: ConnectionsQuotaExceeded for namespace xxx. 276167e3-39ca-49a7-9c7b-0fdd008fe29b_G47 ---> System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: ConnectionsQuotaExceeded for namespace xxx. 276167e3-39ca-49a7-9c7b-0fdd008fe29b_G47

Server stack trace: 
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.ThrowIfFaultMessage(Message wcfMessage)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.HandleMessageReceived(IAsyncResult result)

Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.DuplexCorrelationAsyncResult.End(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass17.<GetAsyncSteps>b__a(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [2]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [3]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpTransactionalAsyncResult`1.<GetAsyncSteps>b__35(TIteratorAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [4]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageSender.EndSendCommand(IAsyncResult result)
   --- End of inner exception stack trace ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.RunSynchronously()
   at Microsoft.ServiceBus.Messaging.MessageSender.Send(TrackingContext trackingContext, IEnumerable`1 messages, TimeSpan timeout)
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueSender.Send(BrokeredMessage brokeredMessage) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\AzureServiceBusQueueSender.cs:line 75
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusSender.SendInternal(TransportMessage message, ISendBrokeredMessages sender, SendOptions options, Boolean expectDelay) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\AzureServiceBusSender.cs:line 57
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusSender.<>c__DisplayClass6_0.<SendInternal>b__0() in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\AzureServiceBusSender.cs:line 45
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.SendResourceManager.Commit(Enlistment enlistment) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\SendResourceManager.cs:line 25

**Comment by SeanFeldman** [comment]
@janpieterz [`QuotaExceededException` ](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-exceptions#quotaexceededexception) is a general one, having details helps. Thank you.

Hard to identify why you're running out of a [1K connections](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas). To understand why this could be happening, could you please provide the following info?

1. What's the number of entities you have in your namespace? (trying to see if number of event X number of subscribers > 1K connections)
1. Is there anything else that connects to this namespace (other test projects, tools, etc)?
1. What's the topology layout?
1. Using tracking IDs provided, could you open a case with MSFT support to identify what entity(s) this was occurring on?

**Comment by janpieterz** [comment]
Sure:

1. 13 Queues, 6 Topics,  25 Subscriptions
2. We have a development tool that sometimes connect to it, though this runs with only one connection. The ServiceBusExplorer connects to it too.  We do have a monitoring tool that connects to it that could be suspect to leaking connections, are you aware of any method of easily diagnosing the connections or is it simply looking at the code until one (possibly) finds it? We've not had any issues like this since or before, while the tool has been running for months (though the same could be said for NSB)
3. 6 Endpoints, running in 1 Azure NSB Host, subscribing to events from each other. No custom connections in that bit.
4. I will
5. Currently no scale out is occuring

**Comment by SeanFeldman** [comment]
@janpieterz based on the info, endpoints are well under the max limit.

I would suggest to install [ASB Performance Counters](https://www.nuget.org/packages/WindowsAzure.ServiceBus.PerformanceCounters) and look at the `MessageFactory Count` counter. It would indicate the number of open connections from a given machine. See what the counter value w/o the support tool reports, and with it.

**Comment by janpieterz** [comment]
@SeanFeldman great stuff, seems like exactly what I needed. 

I've been running around trying to get them running, but since the support tool and the monitoring tool (my highest suspects currently) both don't run in a web rol/worker role (they're just windows service/console tools) I've been unable to get it going. 

Any hint/pointer to get them running in those? Can I run them remotely on my Namespace without having to go into any of the apps?

Or is the only way to get them to add them to the host diagnostics.wadcfg?

**Comment by SeanFeldman** [comment]
This definitely should provide you with a little more details on what's
happening.

Sine these are the client perf counters, they'd need to be presented on the
machine and channeled via diagnostics like any other perf counters.

**Comment by janpieterz** [comment]
Alright. Was hoping I could circumvent updating my NSB host and use any of the other machines as the 'source' for the counters.

**Comment by SeanFeldman** [comment]
You could always RDP into that instance and install these perf counters. Monitoring them would be also as easy as running the PerfMonitor tool. Granted you have RDP enabled and OK with these counters not surviving reboots.

**Comment by janpieterz** [comment]
Just confirmed, only one connection from the monitoring tool during it's whole lifetime.  The endpoints seem to take only about 20 connections (not sure if installing perf counter for one instance counts all connections, I tried 3 of the 6 endpoints and got 20 as the MessageFactory count).

Makes this issue hard to pinpoint of course

**Comment by SeanFeldman** [comment]
@janpieterz just to be sure - when you say "instance" do you mean other machines/VM/service cloud instance? You need to have the counter to be enabled all of them. If you using a shared host, the all multi-hosted endpoints are included. If you scale out number of CS instances, each one of them should have the counter.

**Comment by janpieterz** [comment]
I meant per host environment (only running 1 host with those 6 endpoints for now).
Essentially ran the counters on all VMs where I had anything running that connected to the namespace.

Maybe it was just a fluke from ASB's side, or some scenario slowly had some connections built up that is currently not happening (odd thing was of course that nothing had happened on the environment).

**Comment by SeanFeldman** [comment]
@janpieterz have you got anything from MSFT with those TrackingIDs? They could shed some light at what was happening on the broker? Aside from that, I'm truly out of ideas.

**Comment by janpieterz** [comment]
Nothing specific so far. I think we can close it and if it occurs again or with other people there's some history.
