### ISSUE TITLE
Endpoint stops receiving messages after transport exception

### ISSUE THREAD

**Issue by agiudici1** [Particular/NServiceBus.AzureServiceBus#510]
We are using ASB transport and we observed that for at least 3 different endpoints after an exception from the transport, the endpoint keeps running but it stops receiving messages. The log files for these endpoints show the same event sequence: 

1. WARN NServiceBus.Transport.AzureServiceBus.RepeatedFailuresOverTimeCircuitBreaker
2. WARN NServiceBus.Transport.AzureServiceBus.RepeatedFailuresOverTimeCircuitBreaker
3. ERROR System.OperationCanceledException

Unfortunately, I couldn't reproduce this issue on our dev environment.

We are using these package versions:
NServiceBus v6.1.2
NServiceBus.Azure.Transports.WindowsAzureServiceBus v7.1.1
WindowsAzure.ServiceBus v3.4.5

I don't know if it makes any diffenrece, but we are using ASB Premium Tier.

The full log sequence is the following for all the endpoints:

2017-03-13 08:17:47.586 WARN  NServiceBus.Transport.AzureServiceBus.RepeatedFailuresOverTimeCircuitBreaker The circuit breaker for MessagePump on the queue `1WebAgent.Backend.LongRunningProcesses` is now in the armed state
2017-03-13 08:18:17.648 WARN  NServiceBus.Transport.AzureServiceBus.RepeatedFailuresOverTimeCircuitBreaker The circuit breaker for MessagePump on the queue `1WebAgent.Backend.LongRunningProcesses` will now be triggered
2017-03-13 08:18:17.983 ERROR NServiceBus Failed to receive message from Azure Service Bus.
System.OperationCanceledException: The operation cannot be performed because the entity has been closed or aborted. ---> System.ServiceModel.CommunicationObjectAbortedException: The socket connection was aborted by your local machine. This could be caused by a channel Abort(), or a transmission error from another thread using this socket. ---> System.IO.IOException: The write operation failed, see inner exception. ---> System.ServiceModel.CommunicationObjectAbortedException: The socket connection was aborted by your local machine. This could be caused by a channel Abort(), or a transmission error from another thread using this socket. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.ServiceModel.Channels.SocketConnection.HandleSendAsyncCompleted()
   at System.ServiceModel.Channels.SocketConnection.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, WaitCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.SocketConnection.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, WaitCallback callback, Object state)
   at System.ServiceModel.Channels.BufferedConnection.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, WaitCallback callback, Object state)
   at System.ServiceModel.Channels.ConnectionStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.ServiceModel.Channels.StreamConnection.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, WaitCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.StreamConnection.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, WaitCallback callback, Object state)
   at System.ServiceModel.Channels.FramingDuplexSessionChannel.StartWritingBufferedMessage(Message message, ArraySegment`1 messageData, Boolean allowOutputBatching, TimeSpan timeout, WaitCallback callback, Object state)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.SendAsyncResult.WriteCore()
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.SendAsyncResult..ctor(TransportDuplexSessionChannel channel, Message message, TimeSpan timeout, Boolean streamedOutput, AsyncCallback callback, Object state)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.OnBeginSend(Message message, TimeSpan timeout, AsyncCallback callback, Object state)
   at System.ServiceModel.Channels.OutputChannel.BeginSend(Message message, TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.DuplexCorrelationAsyncResult..ctor(DuplexRequestSessionChannel parent, Message wcfRequest, TimeSpan timeout, AsyncCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass8_1.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<>c.<GetAsyncSteps>b__9_3(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.EndReceiveCommand(IAsyncResult result, IEnumerable`1& messages)
   --- End of inner exception stack trace ---
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.EndReceiveCommand(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.ReceiveAsyncResult.<>c.<GetAsyncSteps>b__12_3(ReceiveAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.OnEndTryReceive(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.<>c.<GetAsyncSteps>b__15_3(RetryReceiveAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.TryReceiveEnd(IAsyncResult r, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndTryReceive(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndReceive(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceivePump.PumpAsyncResult.<>c.<GetAsyncSteps>b__7_3(PumpAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)

**Comment by yvesgoeleven** [comment]
What host are you using?

The default critical error behavior is to stop the message pump, but not the process. If you want to change this behavior so that it crashes the process you can follow the 'custom handling' instructions mentioned here. https://docs.particular.net/nservicebus/hosting/critical-errors

The source of the exception seems to point to a local networking or connectivity issue: "The socket connection was aborted by your local machine"

**Comment by agiudici1** [comment]
We are self hosting as a Webjob in a Azure App Service.

We could try your recommendation, is that a critical error? Meaning that it invokes criticalError.Raise, so we can crash the process?

Thanks

**Comment by yvesgoeleven** [comment]
@agiudici1 exactly, the FailFast call in the example implementation will crash the process as expected

**Comment by agiudici1** [comment]
I'll try that. Thank you.
