### ISSUE TITLE
Exception on shutdown in NServiceBus V5

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#648]
From @ramonsmits 

I'm frequently getting the following with V5:
 ```2017-10-11 09:39:14.1903|FATAL|13|NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueNotifier|Operation cancelled exception occured on receive for queue PerformanceTest, faulting this notifier
System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryAddWithNoTimeValidation(T item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusDequeueStrategy.EnqueueMessage(BrokeredMessage brokeredMessage)
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueNotifier.OnMessage(IAsyncResult ar)
```

This is during shutdown of an endpoint
Due to that..my process exists with an error code
while my main method returned as it should
Seems like a background thread that isn't stopped correctly
would be nice if this could be prevented.

**Comment by ramonsmits** [comment]
@SeanFeldman commented that `OperationCanceledException` would not be V5. Yes, NServiceBus wasn't async but it is using async code.

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/6.4.1/src/Transport/Receiving/AzureServiceBusDequeueStrategy.cs#L300

**Comment by SeanFeldman** [comment]
@ramonsmits  thread based code yes, not async. ASB transport for V5 didn't do anything that was async AFAIK.

As @yvesgoeleven pointed out, if the ASB internally throwing that in one of it's threads, I don't know if this would be caught by our `catch`.

**Comment by SeanFeldman** [comment]
@ramonsmits where does it show up, in the logs or does it bubble up?

**Comment by SeanFeldman** [comment]
Discussed fix: check if token is cancelled before [invoking circuit breaker](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/2599f99b0a4b882b6bdc1679365ea34fc2aa89ee/src/Transport/Receiving/AzureServiceBusDequeueStrategy.cs#L90)

**Comment by ramonsmits** [comment]
@SeanFeldman It only happened at shutdown it seems:

```
2017-10-11 03:28:16.8911|INFO|16|NServiceBus.Unicast.UnicastBus|Initiating shutdown.
2017-10-11 03:28:16.8911|INFO|16|NServiceBus.Satellites.SatelliteLauncher|Stopped 1/1 NServiceBus.SecondLevelRetries.SecondLevelRetriesProcessor, NServiceBus.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c satellite
2017-10-11 03:28:16.8911|INFO|16|NServiceBus.Unicast.UnicastBus|Shutdown complete.
2017-10-11 03:28:16.8911|FATAL|34|NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueNotifier|Operation cancelled exception occured on receive for queue PerformanceTest, faulting this notifier
System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryAddWithNoTimeValidation(T item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusDequeueStrategy.EnqueueMessage(BrokeredMessage brokeredMessage)
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueNotifier.OnMessage(IAsyncResult ar)
2017-10-11 03:28:16.8911|INFO|34|NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusDequeueStrategy|Creating a new notifier for address PerformanceTest@Endpoint=sb://ramon-test-20171005.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=YbHkzVziCXcBOlxaQl2A9G45WfpFPxhpDtis6ZmoMrw=
2017-10-11 03:28:16.8911|INFO|16|Host.Program|Fin!
```

**Comment by SeanFeldman** [comment]
This could be related to the same issue as https://github.com/Particular/NServiceBus.AzureServiceBus/pull/658

**Comment by SeanFeldman** [comment]
Related to #319

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/ff93c3ea2b3cb15b623b96ba8bf14b2ee67f9e5e
