### ISSUE TITLE
MessageTooLargeException is still thrown even when databus(azure) is used

### ISSUE THREAD

**Issue by JSCProjects** [Particular/NServiceBus.AzureServiceBus#653]
For example:

When sending HandleSomeMessageCommand and property DecryptedFileContent is configured as DataBus property a MessageTooLargeException is thrown. See below for the message hierarchy

```
public abstract class HandleInternalCommand<T>
{
	protected HandleInternalCommand(string typeName, T content)
	{
		InternalTypeCommand = typeName;
		Content = content;
	}

	public string InternalTypeCommand { get; }

	public T Content { get; set; }
}

public class HandleSomeMessageCommand : HandleInternalCommand<SomeMessage>
{
	public HandleTinfoCommand(SomeMessage content) : base(nameof(SomeMessage), content)
	{
	}
}

public class SomeMessage
{
	public byte[] DecryptedFileContent { get; set; }
}
```

StackTrace:
```
NServiceBus.Transport.AzureServiceBus.MessageTooLargeException: The message with id ebf11a92-3814-454d-8f28-50806e042317 is larger that the maximum message size allowed by Azure ServiceBus, consider using the databus feature.
   at NServiceBus.Transport.AzureServiceBus.ThrowOnOversizedBrokeredMessages.Handle(BrokeredMessage brokeredMessage) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\ThrowOnOversizedBrokeredMessages.cs:line 10
   at NServiceBus.Transport.AzureServiceBus.DefaultOutgoingBatchRouter.<GuardMessageSizeAsync>d__15.MoveNext() in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\DefaultOutgoingBatchRouter.cs:line 229
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.DefaultOutgoingBatchRouter.<RouteBatchWithEnforcedBatchSizeAsync>d__14.MoveNext() in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\DefaultOutgoingBatchRouter.cs:line 190
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.Transport.AzureServiceBus.DefaultOutgoingBatchRouter.<RouteOutBatchesWithFallbackAndLogExceptionsAsync>d__13.MoveNext() in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\DefaultOutgoingBatchRouter.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NServiceBus.Transport.AzureServiceBus.DefaultOutgoingBatchRouter.<RouteOutBatchesWithFallbackAndLogExceptionsAsync>d__13.MoveNext() in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\DefaultOutgoingBatchRouter.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.Dispatcher.<DispatchWithTransactionScopeIfRequired>d__4.MoveNext() in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Seam\Dispatcher.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.Dispatcher.<DispatchAccordingToIsolationLevel>d__3.MoveNext() in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Seam\Dispatcher.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\MainPipelineExecutor.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.<<Init>b__3_1>d.MoveNext() in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Seam\MessagePump.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.<ProcessMessage>d__13.MoveNext() in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Receiving\MessageReceiverNotifier.cs:line 227
```

**Comment by danielmarbach** [comment]
@JSCProjects can you please try the following:

```
public class SomeMessage
{
	public byte[] DecryptedFileContent { get; set; }
        public string InternalTypeCommand => nameof(SomeMessage);
}
```

and then handle this type directly?

Message hierarchies are known to inflict pain with serializers and data bus.

**Comment by SeanFeldman** [comment]
@JSCProjects have you tried @danielmarbach's suggestion?

**Comment by SeanFeldman** [comment]
@JSCProjects  any updates?

**Comment by SeanFeldman** [comment]
Please re-open if needed.

**Comment by JSCProjects** [comment]
Sorry posted the question a day before my last-minute vacation. I've tried @danielmarbach suggestion and altered it a little bit to make HandleSomeMessageCommand as simple poco and that worked, but I still don't understand why several hundreds of message succeeded.

**Comment by SeanFeldman** [comment]
@JSCProjects any chances you could provide a small repro?

**Comment by JSCProjects** [comment]
@SeanFeldman I don't know what the right variables are te reproduce so it's difficult to make a repro. And I've got more messages like the above and they all work, when I get the issue again I will try to find the right variables and try to make a repro. But for know you can close this issue ;-)

**Comment by danielmarbach** [comment]
For the reference which serializer are you using?

**Comment by JSCProjects** [comment]
We are using JsonSerializer (https://docs.particular.net/nservicebus/serialization/json)

**Comment by dharmeshtailor** [comment]
Actually we are exactly same issue over Azure Service Bus.

`public class EmailAttachment : IDisposable
    {
        public string Name { get; set; }
        public byte[] Data { get; set; }

        [JsonIgnore]
        private MemoryStream _stream;
        [JsonIgnore]
        public MemoryStream Stream
        {
            get
            {
                _stream?.Dispose();
                _stream = new MemoryStream(Data);
                return _stream;
            }
        }

        #region IDisposable Support
        public void Dispose()
        {
            _stream?.Dispose();
        }
        #endregion
    }`

This is the class, we use to send data. 

`var dataBus = endpointConfiguration.UseDataBus<AzureDataBus>();
dataBus.ConnectionString(config.AzureStorageConnectionString);

var transport = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
transport.ConnectionString(config.AzureServiceBusConnectionString);`

**Comment by danielmarbach** [comment]
Does it also fail occasionally like discussed here or reliably all time?

**Comment by JSCProjects** [comment]
Also don't forget to set the right conventions. https://docs.particular.net/nservicebus/messaging/conventions

**Comment by dharmeshtailor** [comment]
> Does it also fail occasionally like discussed here or reliably all time?

Fails always.


> Also don't forget to set the right conventions. https://docs.particular.net/nservicebus/messaging/conventions

Ok I didnt know convention for Databus property. Will give it a try sometime in future, at the moment we changed the implementation to pass the url of the document though.
