### ISSUE TITLE
BrokeredMessageExtension EstimatedSize null exception

### ISSUE THREAD

**Issue by jpalac** [Particular/NServiceBus.AzureServiceBus#800]
In the BrokeredMessageExtension, there's an EstimatedSize method.
When using nservicebus gateway, the BrokeredMessageHeaders.EstimatedMessageSize value is null, and hence this method throws a null exception.

**Comment by danielmarbach** [comment]
hi @jpalac 

I tried to repro the behavior with tests and they all seem to pass https://github.com/Particular/NServiceBus.AzureServiceBus/pull/801

Would you be able to paste the stack trace here from the gateway so that we can have a closer look? Or even better a quick repro if possible?

**Comment by jpalac** [comment]
Daniel,

This happens when doing a context.SendToSites. We have patched the issue on our end so don't have code throwing that error, however I was able to find this log entry from when it happened.

ERROR NServiceBus.Transport.AzureServiceBus.OutgoingBatchRouter [(null)] - Failed to dispatch a batch with the following message IDs: 264951c7-515b-4a3c-b825-7d787b86762c
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToInt64(IFormatProvider provider)
   at NServiceBus.Transport.AzureServiceBus.BrokeredMessageExtensions.EstimatedSize(BrokeredMessage message)
   at NServiceBus.Transport.AzureServiceBus.OutgoingBatchRouter.<GuardMessageSize>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.OutgoingBatchRouter.<RouteBatchWithEnforcedBatchSizeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.AzureServiceBus.OutgoingBatchRouter.<RouteOutBatchesWithFallbackAndLogExceptionsAsync>d__5.MoveNext()

Hope that helps.

**Comment by danielmarbach** [comment]
@jpalac I was able to repro the bug with the gateway. Will investigate further and keep you posted

**Comment by danielmarbach** [comment]
The issue is the following:

For reliability purposes, the gateway sends a message to its local satellite. The satellite then forwards the received message reliably to the remote site and copies all the relevant information to the remote site over HTTP. Azure Service Bus (legacy) has to leverage a property header on the `BrokeredMessage` to indicate the size of the message.

When the transport receives that message on the satellite it extracts the brokered message and tries to map all the properties to `Dictionary<string, string>` by doing

```
            var headers = brokeredMessage.Properties
                .Where(kvp => kvp.Key != BrokeredMessageHeaders.TransportEncoding)
                .ToDictionary(kvp => kvp.Key, kvp => kvp.Value as string);
```

See https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Receiving/BrokeredMessagesToIncomingMessagesConverter.cs#L62-L64

`.Properties` is a type-preserving infrastructure that preserves the estimated transport size that was added as an `Int64` as that type. Now that code tries to weakly cast `Int64` into a string which means the header dictionary will contain `NULL` in the key `NServiceBus.Transport.EstimatedSize`. When transmitted over HTTP the `NULL` value gets turned into `string.Empty` by the [`WebHeaderCollection`](https://referencesource.microsoft.com/#System/net/System/Net/WebHeaderCollection.cs,471) used by the gateway. This value is then tried to be converted into an int64 by the [`BrokeredMessageExtensions](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Utils/BrokeredMessageExtensions.cs#L95`) using the `string` based overload instead of the `object` based overload. An empty string can't be mapped into an int64 which causes that exception.

**Comment by danielmarbach** [comment]
@jpalac we released patch versions of all supported versions of Azure Service Bus that fixes the problem. Thank you very much for reporting it!

https://discuss.particular.net/t/nservicebus-azure-transports-windowsazureservicebus-7-2-16-8-0-7-9-0-4-and-9-1-1-patch-releases-available/929

**Comment by jpalac** [comment]
That's great - thank you!
